version: '2'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-2.0.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  api:
    image: opensdsio/multi-cloud-api
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
    ports:
      - 8089:8089
    environment:
      - MICRO_SERVER_ADDRESS=:8089
      - MICRO_REGISTRY=mdns
      - OS_AUTH_AUTHSTRATEGY=keystone
      - OS_AUTH_URL=http://10.10.3.154/identity
      - OS_USER_DOMIN_ID=Default
      - OS_USERNAME=opensds
      - OS_PASSWORD=opensds@123
      - OS_PROJECT_NAME=service

  backend:
    image: opensdsio/multi-cloud-backend
    environment:
      - MICRO_REGISTRY=mdns
      - DB_HOST=datastore:27017

  s3:
    image: opensdsio/multi-cloud-s3
    environment:
      - MICRO_REGISTRY=mdns
      - DB_HOST=datastore:27017
      # 0 means use user defined storage class, otherwise use default storage class.
      - USE_DEFAULT_STORAGE_CLASS=1

  dataflow:
    image: opensdsio/multi-cloud-dataflow
    environment:
      - MICRO_REGISTRY=mdns
      - DB_HOST=datastore:27017
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
      - kafka

  datamover:
    image: opensdsio/multi-cloud-datamover
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
    environment:
      - MICRO_REGISTRY=mdns
      - DB_HOST=datastore:27017
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      #PARTSIZE for multi-part migration, should not be less than 5(MB) or more than 100(MB)
      - PARTSIZE=16
      #JOB_MAX_RUN_TIME for each migration job, should not be less than 60(second) or more than 2592000(second)
      - JOB_MAX_RUN_TIME=86400
    depends_on:
      - zookeeper
      - kafka

  datastore:
    image: mongo
    ports:
      - 27017:27017
