// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend.proto

package backend

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateBackendRequest struct {
	Context              string         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Backend              *BackendDetail `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateBackendRequest) Reset()         { *m = CreateBackendRequest{} }
func (m *CreateBackendRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBackendRequest) ProtoMessage()    {}
func (*CreateBackendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_backend_32dfbde68d4eaff0, []int{0}
}
func (m *CreateBackendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBackendRequest.Unmarshal(m, b)
}
func (m *CreateBackendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBackendRequest.Marshal(b, m, deterministic)
}
func (dst *CreateBackendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBackendRequest.Merge(dst, src)
}
func (m *CreateBackendRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBackendRequest.Size(m)
}
func (m *CreateBackendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBackendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBackendRequest proto.InternalMessageInfo

func (m *CreateBackendRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *CreateBackendRequest) GetBackend() *BackendDetail {
	if m != nil {
		return m.Backend
	}
	return nil
}

type CreateBackendResponse struct {
	Backend              *BackendDetail `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateBackendResponse) Reset()         { *m = CreateBackendResponse{} }
func (m *CreateBackendResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBackendResponse) ProtoMessage()    {}
func (*CreateBackendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_backend_32dfbde68d4eaff0, []int{1}
}
func (m *CreateBackendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBackendResponse.Unmarshal(m, b)
}
func (m *CreateBackendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBackendResponse.Marshal(b, m, deterministic)
}
func (dst *CreateBackendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBackendResponse.Merge(dst, src)
}
func (m *CreateBackendResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBackendResponse.Size(m)
}
func (m *CreateBackendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBackendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBackendResponse proto.InternalMessageInfo

func (m *CreateBackendResponse) GetBackend() *BackendDetail {
	if m != nil {
		return m.Backend
	}
	return nil
}

type GetBackendRequest struct {
	Context              string   `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBackendRequest) Reset()         { *m = GetBackendRequest{} }
func (m *GetBackendRequest) String() string { return proto.CompactTextString(m) }
func (*GetBackendRequest) ProtoMessage()    {}
func (*GetBackendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_backend_32dfbde68d4eaff0, []int{2}
}
func (m *GetBackendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBackendRequest.Unmarshal(m, b)
}
func (m *GetBackendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBackendRequest.Marshal(b, m, deterministic)
}
func (dst *GetBackendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBackendRequest.Merge(dst, src)
}
func (m *GetBackendRequest) XXX_Size() int {
	return xxx_messageInfo_GetBackendRequest.Size(m)
}
func (m *GetBackendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBackendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBackendRequest proto.InternalMessageInfo

func (m *GetBackendRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *GetBackendRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetBackendResponse struct {
	Backend              *BackendDetail `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetBackendResponse) Reset()         { *m = GetBackendResponse{} }
func (m *GetBackendResponse) String() string { return proto.CompactTextString(m) }
func (*GetBackendResponse) ProtoMessage()    {}
func (*GetBackendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_backend_32dfbde68d4eaff0, []int{3}
}
func (m *GetBackendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBackendResponse.Unmarshal(m, b)
}
func (m *GetBackendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBackendResponse.Marshal(b, m, deterministic)
}
func (dst *GetBackendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBackendResponse.Merge(dst, src)
}
func (m *GetBackendResponse) XXX_Size() int {
	return xxx_messageInfo_GetBackendResponse.Size(m)
}
func (m *GetBackendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBackendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBackendResponse proto.InternalMessageInfo

func (m *GetBackendResponse) GetBackend() *BackendDetail {
	if m != nil {
		return m.Backend
	}
	return nil
}

type ListBackendRequest struct {
	Context              string            `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Limit                int32             `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32             `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	SortKeys             []string          `protobuf:"bytes,4,rep,name=sortKeys,proto3" json:"sortKeys,omitempty"`
	SortDirs             []string          `protobuf:"bytes,5,rep,name=sortDirs,proto3" json:"sortDirs,omitempty"`
	Filter               map[string]string `protobuf:"bytes,6,rep,name=Filter,proto3" json:"Filter,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListBackendRequest) Reset()         { *m = ListBackendRequest{} }
func (m *ListBackendRequest) String() string { return proto.CompactTextString(m) }
func (*ListBackendRequest) ProtoMessage()    {}
func (*ListBackendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_backend_32dfbde68d4eaff0, []int{4}
}
func (m *ListBackendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBackendRequest.Unmarshal(m, b)
}
func (m *ListBackendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBackendRequest.Marshal(b, m, deterministic)
}
func (dst *ListBackendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBackendRequest.Merge(dst, src)
}
func (m *ListBackendRequest) XXX_Size() int {
	return xxx_messageInfo_ListBackendRequest.Size(m)
}
func (m *ListBackendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBackendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBackendRequest proto.InternalMessageInfo

func (m *ListBackendRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *ListBackendRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListBackendRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListBackendRequest) GetSortKeys() []string {
	if m != nil {
		return m.SortKeys
	}
	return nil
}

func (m *ListBackendRequest) GetSortDirs() []string {
	if m != nil {
		return m.SortDirs
	}
	return nil
}

func (m *ListBackendRequest) GetFilter() map[string]string {
	if m != nil {
		return m.Filter
	}
	return nil
}

type ListBackendResponse struct {
	Backends             []*BackendDetail `protobuf:"bytes,1,rep,name=backends,proto3" json:"backends,omitempty"`
	Next                 int32            `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListBackendResponse) Reset()         { *m = ListBackendResponse{} }
func (m *ListBackendResponse) String() string { return proto.CompactTextString(m) }
func (*ListBackendResponse) ProtoMessage()    {}
func (*ListBackendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_backend_32dfbde68d4eaff0, []int{5}
}
func (m *ListBackendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBackendResponse.Unmarshal(m, b)
}
func (m *ListBackendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBackendResponse.Marshal(b, m, deterministic)
}
func (dst *ListBackendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBackendResponse.Merge(dst, src)
}
func (m *ListBackendResponse) XXX_Size() int {
	return xxx_messageInfo_ListBackendResponse.Size(m)
}
func (m *ListBackendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBackendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBackendResponse proto.InternalMessageInfo

func (m *ListBackendResponse) GetBackends() []*BackendDetail {
	if m != nil {
		return m.Backends
	}
	return nil
}

func (m *ListBackendResponse) GetNext() int32 {
	if m != nil {
		return m.Next
	}
	return 0
}

type UpdateBackendRequest struct {
	Context              string   `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Access               string   `protobuf:"bytes,4,opt,name=access,proto3" json:"access,omitempty"`
	Security             string   `protobuf:"bytes,5,opt,name=security,proto3" json:"security,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBackendRequest) Reset()         { *m = UpdateBackendRequest{} }
func (m *UpdateBackendRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBackendRequest) ProtoMessage()    {}
func (*UpdateBackendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_backend_32dfbde68d4eaff0, []int{6}
}
func (m *UpdateBackendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBackendRequest.Unmarshal(m, b)
}
func (m *UpdateBackendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBackendRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateBackendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBackendRequest.Merge(dst, src)
}
func (m *UpdateBackendRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBackendRequest.Size(m)
}
func (m *UpdateBackendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBackendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBackendRequest proto.InternalMessageInfo

func (m *UpdateBackendRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *UpdateBackendRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateBackendRequest) GetAccess() string {
	if m != nil {
		return m.Access
	}
	return ""
}

func (m *UpdateBackendRequest) GetSecurity() string {
	if m != nil {
		return m.Security
	}
	return ""
}

type UpdateBackendResponse struct {
	Backend              *BackendDetail `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateBackendResponse) Reset()         { *m = UpdateBackendResponse{} }
func (m *UpdateBackendResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateBackendResponse) ProtoMessage()    {}
func (*UpdateBackendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_backend_32dfbde68d4eaff0, []int{7}
}
func (m *UpdateBackendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBackendResponse.Unmarshal(m, b)
}
func (m *UpdateBackendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBackendResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateBackendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBackendResponse.Merge(dst, src)
}
func (m *UpdateBackendResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateBackendResponse.Size(m)
}
func (m *UpdateBackendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBackendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBackendResponse proto.InternalMessageInfo

func (m *UpdateBackendResponse) GetBackend() *BackendDetail {
	if m != nil {
		return m.Backend
	}
	return nil
}

type DeleteBackendRequest struct {
	Context              string   `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBackendRequest) Reset()         { *m = DeleteBackendRequest{} }
func (m *DeleteBackendRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBackendRequest) ProtoMessage()    {}
func (*DeleteBackendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_backend_32dfbde68d4eaff0, []int{8}
}
func (m *DeleteBackendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBackendRequest.Unmarshal(m, b)
}
func (m *DeleteBackendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBackendRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteBackendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBackendRequest.Merge(dst, src)
}
func (m *DeleteBackendRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBackendRequest.Size(m)
}
func (m *DeleteBackendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBackendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBackendRequest proto.InternalMessageInfo

func (m *DeleteBackendRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *DeleteBackendRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteBackendResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBackendResponse) Reset()         { *m = DeleteBackendResponse{} }
func (m *DeleteBackendResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBackendResponse) ProtoMessage()    {}
func (*DeleteBackendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_backend_32dfbde68d4eaff0, []int{9}
}
func (m *DeleteBackendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBackendResponse.Unmarshal(m, b)
}
func (m *DeleteBackendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBackendResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteBackendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBackendResponse.Merge(dst, src)
}
func (m *DeleteBackendResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBackendResponse.Size(m)
}
func (m *DeleteBackendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBackendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBackendResponse proto.InternalMessageInfo

type BackendDetail struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId             string   `protobuf:"bytes,2,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Region               string   `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	Endpoint             string   `protobuf:"bytes,7,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	BucketName           string   `protobuf:"bytes,8,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	Access               string   `protobuf:"bytes,9,opt,name=access,proto3" json:"access,omitempty"`
	Security             string   `protobuf:"bytes,10,opt,name=security,proto3" json:"security,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackendDetail) Reset()         { *m = BackendDetail{} }
func (m *BackendDetail) String() string { return proto.CompactTextString(m) }
func (*BackendDetail) ProtoMessage()    {}
func (*BackendDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_backend_32dfbde68d4eaff0, []int{10}
}
func (m *BackendDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendDetail.Unmarshal(m, b)
}
func (m *BackendDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendDetail.Marshal(b, m, deterministic)
}
func (dst *BackendDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendDetail.Merge(dst, src)
}
func (m *BackendDetail) XXX_Size() int {
	return xxx_messageInfo_BackendDetail.Size(m)
}
func (m *BackendDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendDetail.DiscardUnknown(m)
}

var xxx_messageInfo_BackendDetail proto.InternalMessageInfo

func (m *BackendDetail) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BackendDetail) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *BackendDetail) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *BackendDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BackendDetail) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *BackendDetail) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *BackendDetail) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *BackendDetail) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *BackendDetail) GetAccess() string {
	if m != nil {
		return m.Access
	}
	return ""
}

func (m *BackendDetail) GetSecurity() string {
	if m != nil {
		return m.Security
	}
	return ""
}

type ListTypeRequest struct {
	Context              string            `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Limit                int32             `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32             `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	SortKeys             []string          `protobuf:"bytes,4,rep,name=sortKeys,proto3" json:"sortKeys,omitempty"`
	SortDirs             []string          `protobuf:"bytes,5,rep,name=sortDirs,proto3" json:"sortDirs,omitempty"`
	Filter               map[string]string `protobuf:"bytes,6,rep,name=Filter,proto3" json:"Filter,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListTypeRequest) Reset()         { *m = ListTypeRequest{} }
func (m *ListTypeRequest) String() string { return proto.CompactTextString(m) }
func (*ListTypeRequest) ProtoMessage()    {}
func (*ListTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_backend_32dfbde68d4eaff0, []int{11}
}
func (m *ListTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTypeRequest.Unmarshal(m, b)
}
func (m *ListTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTypeRequest.Marshal(b, m, deterministic)
}
func (dst *ListTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTypeRequest.Merge(dst, src)
}
func (m *ListTypeRequest) XXX_Size() int {
	return xxx_messageInfo_ListTypeRequest.Size(m)
}
func (m *ListTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTypeRequest proto.InternalMessageInfo

func (m *ListTypeRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *ListTypeRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListTypeRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListTypeRequest) GetSortKeys() []string {
	if m != nil {
		return m.SortKeys
	}
	return nil
}

func (m *ListTypeRequest) GetSortDirs() []string {
	if m != nil {
		return m.SortDirs
	}
	return nil
}

func (m *ListTypeRequest) GetFilter() map[string]string {
	if m != nil {
		return m.Filter
	}
	return nil
}

type ListTypeResponse struct {
	Types                []*TypeDetail `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	Next                 int32         `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListTypeResponse) Reset()         { *m = ListTypeResponse{} }
func (m *ListTypeResponse) String() string { return proto.CompactTextString(m) }
func (*ListTypeResponse) ProtoMessage()    {}
func (*ListTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_backend_32dfbde68d4eaff0, []int{12}
}
func (m *ListTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTypeResponse.Unmarshal(m, b)
}
func (m *ListTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTypeResponse.Marshal(b, m, deterministic)
}
func (dst *ListTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTypeResponse.Merge(dst, src)
}
func (m *ListTypeResponse) XXX_Size() int {
	return xxx_messageInfo_ListTypeResponse.Size(m)
}
func (m *ListTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTypeResponse proto.InternalMessageInfo

func (m *ListTypeResponse) GetTypes() []*TypeDetail {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *ListTypeResponse) GetNext() int32 {
	if m != nil {
		return m.Next
	}
	return 0
}

type TypeDetail struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeDetail) Reset()         { *m = TypeDetail{} }
func (m *TypeDetail) String() string { return proto.CompactTextString(m) }
func (*TypeDetail) ProtoMessage()    {}
func (*TypeDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_backend_32dfbde68d4eaff0, []int{13}
}
func (m *TypeDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeDetail.Unmarshal(m, b)
}
func (m *TypeDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeDetail.Marshal(b, m, deterministic)
}
func (dst *TypeDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeDetail.Merge(dst, src)
}
func (m *TypeDetail) XXX_Size() int {
	return xxx_messageInfo_TypeDetail.Size(m)
}
func (m *TypeDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeDetail.DiscardUnknown(m)
}

var xxx_messageInfo_TypeDetail proto.InternalMessageInfo

func (m *TypeDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TypeDetail) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateBackendRequest)(nil), "CreateBackendRequest")
	proto.RegisterType((*CreateBackendResponse)(nil), "CreateBackendResponse")
	proto.RegisterType((*GetBackendRequest)(nil), "GetBackendRequest")
	proto.RegisterType((*GetBackendResponse)(nil), "GetBackendResponse")
	proto.RegisterType((*ListBackendRequest)(nil), "ListBackendRequest")
	proto.RegisterMapType((map[string]string)(nil), "ListBackendRequest.FilterEntry")
	proto.RegisterType((*ListBackendResponse)(nil), "ListBackendResponse")
	proto.RegisterType((*UpdateBackendRequest)(nil), "UpdateBackendRequest")
	proto.RegisterType((*UpdateBackendResponse)(nil), "UpdateBackendResponse")
	proto.RegisterType((*DeleteBackendRequest)(nil), "DeleteBackendRequest")
	proto.RegisterType((*DeleteBackendResponse)(nil), "DeleteBackendResponse")
	proto.RegisterType((*BackendDetail)(nil), "BackendDetail")
	proto.RegisterType((*ListTypeRequest)(nil), "ListTypeRequest")
	proto.RegisterMapType((map[string]string)(nil), "ListTypeRequest.FilterEntry")
	proto.RegisterType((*ListTypeResponse)(nil), "ListTypeResponse")
	proto.RegisterType((*TypeDetail)(nil), "TypeDetail")
}

func init() { proto.RegisterFile("backend.proto", fileDescriptor_backend_32dfbde68d4eaff0) }

var fileDescriptor_backend_32dfbde68d4eaff0 = []byte{
	// 649 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0x4b, 0x6f, 0xd3, 0x40,
	0x10, 0x8e, 0x9d, 0xe6, 0x35, 0x56, 0x4b, 0xbb, 0x4d, 0x82, 0x65, 0x21, 0x08, 0x3e, 0x45, 0x1c,
	0x56, 0xa2, 0x20, 0x15, 0x2a, 0x81, 0x4a, 0x29, 0xa0, 0x0a, 0xc4, 0xc1, 0xa2, 0x17, 0x6e, 0xae,
	0x3d, 0x45, 0xab, 0xa6, 0xb6, 0xf1, 0x6e, 0x10, 0xbe, 0xc2, 0x85, 0x7f, 0xcc, 0x15, 0xed, 0xc3,
	0x8e, 0xe3, 0x1a, 0xd4, 0x22, 0x0e, 0xdc, 0xf6, 0x9b, 0xf1, 0xce, 0x7c, 0xfe, 0xe6, 0xb1, 0xb0,
	0x79, 0x16, 0x46, 0x17, 0x98, 0xc4, 0x34, 0xcb, 0x53, 0x91, 0xfa, 0x1f, 0x61, 0xfc, 0x32, 0xc7,
	0x50, 0xe0, 0x91, 0x36, 0x07, 0xf8, 0x79, 0x89, 0x5c, 0x10, 0x17, 0x06, 0x51, 0x9a, 0x08, 0xfc,
	0x2a, 0x5c, 0x6b, 0x66, 0xcd, 0x47, 0x41, 0x09, 0xc9, 0x1c, 0x06, 0x26, 0x84, 0x6b, 0xcf, 0xac,
	0xb9, 0xb3, 0xb7, 0x45, 0xcd, 0xdd, 0x63, 0x14, 0x21, 0x5b, 0x04, 0xa5, 0xdb, 0x7f, 0x01, 0x93,
	0x46, 0x6c, 0x9e, 0xa5, 0x09, 0xc7, 0x7a, 0x08, 0xeb, 0xcf, 0x21, 0x9e, 0xc1, 0xce, 0x1b, 0x14,
	0xd7, 0xe6, 0xb6, 0x05, 0x36, 0xd3, 0xb4, 0x46, 0x81, 0xcd, 0x62, 0xff, 0x39, 0x90, 0xfa, 0xf5,
	0x1b, 0xa7, 0xff, 0x61, 0x03, 0x79, 0xc7, 0xf8, 0xf5, 0x09, 0x8c, 0xa1, 0xb7, 0x60, 0x97, 0x4c,
	0x28, 0x0e, 0xbd, 0x40, 0x03, 0x32, 0x85, 0x7e, 0x7a, 0x7e, 0xce, 0x51, 0xb8, 0x5d, 0x65, 0x36,
	0x88, 0x78, 0x30, 0xe4, 0x69, 0x2e, 0xde, 0x62, 0xc1, 0xdd, 0x8d, 0x59, 0x77, 0x3e, 0x0a, 0x2a,
	0x5c, 0xfa, 0x8e, 0x59, 0xce, 0xdd, 0xde, 0xca, 0x27, 0x31, 0xd9, 0x87, 0xfe, 0x6b, 0xb6, 0x10,
	0x98, 0xbb, 0xfd, 0x59, 0x77, 0xee, 0xec, 0xdd, 0xa3, 0x57, 0x49, 0x52, 0xfd, 0xc5, 0xab, 0x44,
	0xe4, 0x45, 0x60, 0x3e, 0xf7, 0x9e, 0x82, 0x53, 0x33, 0x93, 0x6d, 0xe8, 0x5e, 0x60, 0x61, 0xfe,
	0x41, 0x1e, 0x25, 0xff, 0x2f, 0xe1, 0x62, 0x89, 0x46, 0x43, 0x0d, 0x0e, 0xec, 0x27, 0x96, 0x7f,
	0x0a, 0xbb, 0x6b, 0x49, 0x8c, 0x96, 0x0f, 0x60, 0x68, 0xc4, 0xe2, 0xae, 0xa5, 0xc8, 0x34, 0xc5,
	0xac, 0xfc, 0x84, 0xc0, 0x46, 0x22, 0x35, 0xd3, 0xda, 0xa8, 0xb3, 0x2f, 0x60, 0x7c, 0x9a, 0xc5,
	0x37, 0xe9, 0xbf, 0x46, 0x8d, 0xa5, 0xb8, 0x61, 0x14, 0x21, 0x97, 0x12, 0x4a, 0x9b, 0x41, 0x4a,
	0x40, 0x8c, 0x96, 0x39, 0x13, 0x85, 0xdb, 0x53, 0x9e, 0x0a, 0xcb, 0xce, 0x6c, 0x64, 0xbd, 0x71,
	0x6b, 0x1c, 0xc2, 0xf8, 0x18, 0x17, 0xf8, 0xf7, 0xc4, 0xfd, 0xdb, 0x30, 0x69, 0x44, 0xd0, 0x24,
	0xfc, 0xef, 0x36, 0x6c, 0xae, 0x65, 0x35, 0x57, 0xad, 0xea, 0x9f, 0x3d, 0x18, 0x0a, 0x4c, 0xc2,
	0x44, 0x9c, 0x94, 0x01, 0x2b, 0x2c, 0xf5, 0x58, 0x72, 0xcc, 0x4f, 0x62, 0xd5, 0x6c, 0xa3, 0xc0,
	0x20, 0xa5, 0x7e, 0x78, 0x89, 0x46, 0x25, 0x75, 0x96, 0x36, 0x51, 0x64, 0x68, 0xf4, 0x51, 0x67,
	0x79, 0x3f, 0xc7, 0x4f, 0x2c, 0x4d, 0xdc, 0xbe, 0xbe, 0xaf, 0x91, 0xcc, 0x89, 0x49, 0x9c, 0xa5,
	0x2c, 0x11, 0xee, 0x40, 0xe7, 0x2c, 0x31, 0xb9, 0x0b, 0x70, 0xb6, 0x8c, 0x2e, 0x50, 0xbc, 0x97,
	0x19, 0x86, 0xca, 0x5b, 0xb3, 0xd4, 0x6a, 0x34, 0xfa, 0x6d, 0x8d, 0xa0, 0x51, 0xa3, 0x6f, 0x36,
	0xdc, 0x92, 0x1d, 0xf7, 0xa1, 0xc8, 0xf0, 0x7f, 0x19, 0xbc, 0xc7, 0x8d, 0xc1, 0xbb, 0x43, 0x1b,
	0x0c, 0xff, 0xf5, 0xd4, 0x9d, 0xc0, 0xf6, 0x2a, 0x83, 0xe9, 0xd1, 0xfb, 0xd0, 0x93, 0x85, 0x2a,
	0xe7, 0xcd, 0xa1, 0xd2, 0x6b, 0xda, 0x53, 0x7b, 0x5a, 0x27, 0xed, 0x08, 0x60, 0xf5, 0x61, 0xd5,
	0x0d, 0x56, 0xad, 0x1b, 0x66, 0xe0, 0xc4, 0xc8, 0xa3, 0x9c, 0x65, 0x42, 0x96, 0x5f, 0x93, 0xa9,
	0x9b, 0xf6, 0x7e, 0xda, 0x30, 0x30, 0x9d, 0x49, 0x0e, 0x61, 0x73, 0x6d, 0xbb, 0x93, 0x09, 0x6d,
	0x7b, 0x49, 0xbc, 0x29, 0x6d, 0x7d, 0x04, 0xfc, 0x0e, 0xd9, 0x07, 0x58, 0x6d, 0x67, 0x42, 0xe8,
	0x95, 0x4d, 0xef, 0xed, 0xd2, 0xab, 0xeb, 0xdb, 0xef, 0x90, 0x03, 0x70, 0x6a, 0xbb, 0x88, 0xec,
	0xb6, 0xac, 0x3f, 0x6f, 0x4c, 0x5b, 0xd6, 0x95, 0xdf, 0x91, 0xb4, 0xd7, 0x46, 0x9f, 0x4c, 0x68,
	0xdb, 0x02, 0xf2, 0xa6, 0xb4, 0x75, 0x43, 0xe8, 0x08, 0x6b, 0x73, 0x4b, 0x26, 0xb4, 0x6d, 0x13,
	0x78, 0x53, 0xda, 0x3e, 0xde, 0x1d, 0xf2, 0x10, 0x86, 0x65, 0x55, 0xc9, 0x76, 0xb3, 0x85, 0xbc,
	0x1d, 0xda, 0x2c, 0xb9, 0xdf, 0x39, 0xeb, 0xab, 0xe7, 0xfa, 0xd1, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xf6, 0x06, 0x55, 0x74, 0xbf, 0x07, 0x00, 0x00,
}
