// Code generated by protoc-gen-go. DO NOT EDIT.
// source: s3.proto

package s3

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ACL struct {
	Canned               string   `protobuf:"bytes,1,opt,name=canned,proto3" json:"canned,omitempty"`
	FULL_CONTROL         []string `protobuf:"bytes,2,rep,name=FULL_CONTROL,json=FULLCONTROL,proto3" json:"FULL_CONTROL,omitempty"`
	WRITE                []string `protobuf:"bytes,3,rep,name=WRITE,proto3" json:"WRITE,omitempty"`
	WRITE_ACP            []string `protobuf:"bytes,4,rep,name=WRITE_ACP,json=WRITEACP,proto3" json:"WRITE_ACP,omitempty"`
	READ                 []string `protobuf:"bytes,5,rep,name=READ,proto3" json:"READ,omitempty"`
	READ_ACP             []string `protobuf:"bytes,6,rep,name=READ_ACP,json=READACP,proto3" json:"READ_ACP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ACL) Reset()         { *m = ACL{} }
func (m *ACL) String() string { return proto.CompactTextString(m) }
func (*ACL) ProtoMessage()    {}
func (*ACL) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{0}
}
func (m *ACL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACL.Unmarshal(m, b)
}
func (m *ACL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACL.Marshal(b, m, deterministic)
}
func (dst *ACL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACL.Merge(dst, src)
}
func (m *ACL) XXX_Size() int {
	return xxx_messageInfo_ACL.Size(m)
}
func (m *ACL) XXX_DiscardUnknown() {
	xxx_messageInfo_ACL.DiscardUnknown(m)
}

var xxx_messageInfo_ACL proto.InternalMessageInfo

func (m *ACL) GetCanned() string {
	if m != nil {
		return m.Canned
	}
	return ""
}

func (m *ACL) GetFULL_CONTROL() []string {
	if m != nil {
		return m.FULL_CONTROL
	}
	return nil
}

func (m *ACL) GetWRITE() []string {
	if m != nil {
		return m.WRITE
	}
	return nil
}

func (m *ACL) GetWRITE_ACP() []string {
	if m != nil {
		return m.WRITE_ACP
	}
	return nil
}

func (m *ACL) GetREAD() []string {
	if m != nil {
		return m.READ
	}
	return nil
}

func (m *ACL) GetREAD_ACP() []string {
	if m != nil {
		return m.READ_ACP
	}
	return nil
}

type ServerSideEncryption struct {
	CryptScheme          string   `protobuf:"bytes,1,opt,name=cryptScheme,proto3" json:"cryptScheme,omitempty"`
	Algorithm            string   `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	MasterKeyId          string   `protobuf:"bytes,3,opt,name=masterKeyId,proto3" json:"masterKeyId,omitempty"`
	Mandtory             bool     `protobuf:"varint,4,opt,name=mandtory,proto3" json:"mandtory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerSideEncryption) Reset()         { *m = ServerSideEncryption{} }
func (m *ServerSideEncryption) String() string { return proto.CompactTextString(m) }
func (*ServerSideEncryption) ProtoMessage()    {}
func (*ServerSideEncryption) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{1}
}
func (m *ServerSideEncryption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerSideEncryption.Unmarshal(m, b)
}
func (m *ServerSideEncryption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerSideEncryption.Marshal(b, m, deterministic)
}
func (dst *ServerSideEncryption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerSideEncryption.Merge(dst, src)
}
func (m *ServerSideEncryption) XXX_Size() int {
	return xxx_messageInfo_ServerSideEncryption.Size(m)
}
func (m *ServerSideEncryption) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerSideEncryption.DiscardUnknown(m)
}

var xxx_messageInfo_ServerSideEncryption proto.InternalMessageInfo

func (m *ServerSideEncryption) GetCryptScheme() string {
	if m != nil {
		return m.CryptScheme
	}
	return ""
}

func (m *ServerSideEncryption) GetAlgorithm() string {
	if m != nil {
		return m.Algorithm
	}
	return ""
}

func (m *ServerSideEncryption) GetMasterKeyId() string {
	if m != nil {
		return m.MasterKeyId
	}
	return ""
}

func (m *ServerSideEncryption) GetMandtory() bool {
	if m != nil {
		return m.Mandtory
	}
	return false
}

type VersioningConfiguration struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	MfaDelete            string   `protobuf:"bytes,2,opt,name=MfaDelete,proto3" json:"MfaDelete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersioningConfiguration) Reset()         { *m = VersioningConfiguration{} }
func (m *VersioningConfiguration) String() string { return proto.CompactTextString(m) }
func (*VersioningConfiguration) ProtoMessage()    {}
func (*VersioningConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{2}
}
func (m *VersioningConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersioningConfiguration.Unmarshal(m, b)
}
func (m *VersioningConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersioningConfiguration.Marshal(b, m, deterministic)
}
func (dst *VersioningConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersioningConfiguration.Merge(dst, src)
}
func (m *VersioningConfiguration) XXX_Size() int {
	return xxx_messageInfo_VersioningConfiguration.Size(m)
}
func (m *VersioningConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_VersioningConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_VersioningConfiguration proto.InternalMessageInfo

func (m *VersioningConfiguration) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *VersioningConfiguration) GetMfaDelete() string {
	if m != nil {
		return m.MfaDelete
	}
	return ""
}

type RedirectAllRequestsTo struct {
	HostName             string   `protobuf:"bytes,1,opt,name=hostName,proto3" json:"hostName,omitempty"`
	Protocol             []string `protobuf:"bytes,2,rep,name=protocol,proto3" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedirectAllRequestsTo) Reset()         { *m = RedirectAllRequestsTo{} }
func (m *RedirectAllRequestsTo) String() string { return proto.CompactTextString(m) }
func (*RedirectAllRequestsTo) ProtoMessage()    {}
func (*RedirectAllRequestsTo) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{3}
}
func (m *RedirectAllRequestsTo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedirectAllRequestsTo.Unmarshal(m, b)
}
func (m *RedirectAllRequestsTo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedirectAllRequestsTo.Marshal(b, m, deterministic)
}
func (dst *RedirectAllRequestsTo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedirectAllRequestsTo.Merge(dst, src)
}
func (m *RedirectAllRequestsTo) XXX_Size() int {
	return xxx_messageInfo_RedirectAllRequestsTo.Size(m)
}
func (m *RedirectAllRequestsTo) XXX_DiscardUnknown() {
	xxx_messageInfo_RedirectAllRequestsTo.DiscardUnknown(m)
}

var xxx_messageInfo_RedirectAllRequestsTo proto.InternalMessageInfo

func (m *RedirectAllRequestsTo) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *RedirectAllRequestsTo) GetProtocol() []string {
	if m != nil {
		return m.Protocol
	}
	return nil
}

type Redirect struct {
	Protocol             string   `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	HostName             string   `protobuf:"bytes,2,opt,name=hostName,proto3" json:"hostName,omitempty"`
	ReplaceKeyPrefixWith string   `protobuf:"bytes,3,opt,name=replaceKeyPrefixWith,proto3" json:"replaceKeyPrefixWith,omitempty"`
	ReplaceKeyWith       string   `protobuf:"bytes,4,opt,name=replaceKeyWith,proto3" json:"replaceKeyWith,omitempty"`
	HttpRedirectCode     string   `protobuf:"bytes,5,opt,name=httpRedirectCode,proto3" json:"httpRedirectCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Redirect) Reset()         { *m = Redirect{} }
func (m *Redirect) String() string { return proto.CompactTextString(m) }
func (*Redirect) ProtoMessage()    {}
func (*Redirect) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{4}
}
func (m *Redirect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Redirect.Unmarshal(m, b)
}
func (m *Redirect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Redirect.Marshal(b, m, deterministic)
}
func (dst *Redirect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Redirect.Merge(dst, src)
}
func (m *Redirect) XXX_Size() int {
	return xxx_messageInfo_Redirect.Size(m)
}
func (m *Redirect) XXX_DiscardUnknown() {
	xxx_messageInfo_Redirect.DiscardUnknown(m)
}

var xxx_messageInfo_Redirect proto.InternalMessageInfo

func (m *Redirect) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Redirect) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *Redirect) GetReplaceKeyPrefixWith() string {
	if m != nil {
		return m.ReplaceKeyPrefixWith
	}
	return ""
}

func (m *Redirect) GetReplaceKeyWith() string {
	if m != nil {
		return m.ReplaceKeyWith
	}
	return ""
}

func (m *Redirect) GetHttpRedirectCode() string {
	if m != nil {
		return m.HttpRedirectCode
	}
	return ""
}

type Condition struct {
	KeyPrefixEquals             string   `protobuf:"bytes,1,opt,name=keyPrefixEquals,proto3" json:"keyPrefixEquals,omitempty"`
	HttpErrorCodeReturnedEquals string   `protobuf:"bytes,2,opt,name=httpErrorCodeReturnedEquals,proto3" json:"httpErrorCodeReturnedEquals,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *Condition) Reset()         { *m = Condition{} }
func (m *Condition) String() string { return proto.CompactTextString(m) }
func (*Condition) ProtoMessage()    {}
func (*Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{5}
}
func (m *Condition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Condition.Unmarshal(m, b)
}
func (m *Condition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Condition.Marshal(b, m, deterministic)
}
func (dst *Condition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Condition.Merge(dst, src)
}
func (m *Condition) XXX_Size() int {
	return xxx_messageInfo_Condition.Size(m)
}
func (m *Condition) XXX_DiscardUnknown() {
	xxx_messageInfo_Condition.DiscardUnknown(m)
}

var xxx_messageInfo_Condition proto.InternalMessageInfo

func (m *Condition) GetKeyPrefixEquals() string {
	if m != nil {
		return m.KeyPrefixEquals
	}
	return ""
}

func (m *Condition) GetHttpErrorCodeReturnedEquals() string {
	if m != nil {
		return m.HttpErrorCodeReturnedEquals
	}
	return ""
}

type RoutingRules struct {
	Redirect             *Redirect  `protobuf:"bytes,1,opt,name=redirect,proto3" json:"redirect,omitempty"`
	Condition            *Condition `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RoutingRules) Reset()         { *m = RoutingRules{} }
func (m *RoutingRules) String() string { return proto.CompactTextString(m) }
func (*RoutingRules) ProtoMessage()    {}
func (*RoutingRules) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{6}
}
func (m *RoutingRules) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoutingRules.Unmarshal(m, b)
}
func (m *RoutingRules) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoutingRules.Marshal(b, m, deterministic)
}
func (dst *RoutingRules) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoutingRules.Merge(dst, src)
}
func (m *RoutingRules) XXX_Size() int {
	return xxx_messageInfo_RoutingRules.Size(m)
}
func (m *RoutingRules) XXX_DiscardUnknown() {
	xxx_messageInfo_RoutingRules.DiscardUnknown(m)
}

var xxx_messageInfo_RoutingRules proto.InternalMessageInfo

func (m *RoutingRules) GetRedirect() *Redirect {
	if m != nil {
		return m.Redirect
	}
	return nil
}

func (m *RoutingRules) GetCondition() *Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

type WebsiteConfiguration struct {
	IndexDocument         string                 `protobuf:"bytes,1,opt,name=indexDocument,proto3" json:"indexDocument,omitempty"`
	ErrorDocument         string                 `protobuf:"bytes,2,opt,name=errorDocument,proto3" json:"errorDocument,omitempty"`
	RedirectAllRequestsTo *RedirectAllRequestsTo `protobuf:"bytes,3,opt,name=redirectAllRequestsTo,proto3" json:"redirectAllRequestsTo,omitempty"`
	RoutingRules          []*RoutingRules        `protobuf:"bytes,4,rep,name=routingRules,proto3" json:"routingRules,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *WebsiteConfiguration) Reset()         { *m = WebsiteConfiguration{} }
func (m *WebsiteConfiguration) String() string { return proto.CompactTextString(m) }
func (*WebsiteConfiguration) ProtoMessage()    {}
func (*WebsiteConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{7}
}
func (m *WebsiteConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebsiteConfiguration.Unmarshal(m, b)
}
func (m *WebsiteConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebsiteConfiguration.Marshal(b, m, deterministic)
}
func (dst *WebsiteConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebsiteConfiguration.Merge(dst, src)
}
func (m *WebsiteConfiguration) XXX_Size() int {
	return xxx_messageInfo_WebsiteConfiguration.Size(m)
}
func (m *WebsiteConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_WebsiteConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_WebsiteConfiguration proto.InternalMessageInfo

func (m *WebsiteConfiguration) GetIndexDocument() string {
	if m != nil {
		return m.IndexDocument
	}
	return ""
}

func (m *WebsiteConfiguration) GetErrorDocument() string {
	if m != nil {
		return m.ErrorDocument
	}
	return ""
}

func (m *WebsiteConfiguration) GetRedirectAllRequestsTo() *RedirectAllRequestsTo {
	if m != nil {
		return m.RedirectAllRequestsTo
	}
	return nil
}

func (m *WebsiteConfiguration) GetRoutingRules() []*RoutingRules {
	if m != nil {
		return m.RoutingRules
	}
	return nil
}

type CORSConfiguration struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AllowedMethods       string   `protobuf:"bytes,2,opt,name=allowedMethods,proto3" json:"allowedMethods,omitempty"`
	AllowedOrigins       string   `protobuf:"bytes,3,opt,name=allowedOrigins,proto3" json:"allowedOrigins,omitempty"`
	AllowedHeaders       string   `protobuf:"bytes,4,opt,name=allowedHeaders,proto3" json:"allowedHeaders,omitempty"`
	MaxAgeSeconds        string   `protobuf:"bytes,5,opt,name=maxAgeSeconds,proto3" json:"maxAgeSeconds,omitempty"`
	ExposedHeaders       string   `protobuf:"bytes,6,opt,name=exposedHeaders,proto3" json:"exposedHeaders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CORSConfiguration) Reset()         { *m = CORSConfiguration{} }
func (m *CORSConfiguration) String() string { return proto.CompactTextString(m) }
func (*CORSConfiguration) ProtoMessage()    {}
func (*CORSConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{8}
}
func (m *CORSConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CORSConfiguration.Unmarshal(m, b)
}
func (m *CORSConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CORSConfiguration.Marshal(b, m, deterministic)
}
func (dst *CORSConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CORSConfiguration.Merge(dst, src)
}
func (m *CORSConfiguration) XXX_Size() int {
	return xxx_messageInfo_CORSConfiguration.Size(m)
}
func (m *CORSConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_CORSConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_CORSConfiguration proto.InternalMessageInfo

func (m *CORSConfiguration) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CORSConfiguration) GetAllowedMethods() string {
	if m != nil {
		return m.AllowedMethods
	}
	return ""
}

func (m *CORSConfiguration) GetAllowedOrigins() string {
	if m != nil {
		return m.AllowedOrigins
	}
	return ""
}

func (m *CORSConfiguration) GetAllowedHeaders() string {
	if m != nil {
		return m.AllowedHeaders
	}
	return ""
}

func (m *CORSConfiguration) GetMaxAgeSeconds() string {
	if m != nil {
		return m.MaxAgeSeconds
	}
	return ""
}

func (m *CORSConfiguration) GetExposedHeaders() string {
	if m != nil {
		return m.ExposedHeaders
	}
	return ""
}

type Destination struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	StorageClass         string   `protobuf:"bytes,2,opt,name=storageClass,proto3" json:"storageClass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Destination) Reset()         { *m = Destination{} }
func (m *Destination) String() string { return proto.CompactTextString(m) }
func (*Destination) ProtoMessage()    {}
func (*Destination) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{9}
}
func (m *Destination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Destination.Unmarshal(m, b)
}
func (m *Destination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Destination.Marshal(b, m, deterministic)
}
func (dst *Destination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Destination.Merge(dst, src)
}
func (m *Destination) XXX_Size() int {
	return xxx_messageInfo_Destination.Size(m)
}
func (m *Destination) XXX_DiscardUnknown() {
	xxx_messageInfo_Destination.DiscardUnknown(m)
}

var xxx_messageInfo_Destination proto.InternalMessageInfo

func (m *Destination) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *Destination) GetStorageClass() string {
	if m != nil {
		return m.StorageClass
	}
	return ""
}

type ReplicationRole struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Prefix               string       `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Enabled              bool         `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Destination          *Destination `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplicationRole) Reset()         { *m = ReplicationRole{} }
func (m *ReplicationRole) String() string { return proto.CompactTextString(m) }
func (*ReplicationRole) ProtoMessage()    {}
func (*ReplicationRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{10}
}
func (m *ReplicationRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicationRole.Unmarshal(m, b)
}
func (m *ReplicationRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicationRole.Marshal(b, m, deterministic)
}
func (dst *ReplicationRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationRole.Merge(dst, src)
}
func (m *ReplicationRole) XXX_Size() int {
	return xxx_messageInfo_ReplicationRole.Size(m)
}
func (m *ReplicationRole) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationRole.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationRole proto.InternalMessageInfo

func (m *ReplicationRole) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReplicationRole) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *ReplicationRole) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *ReplicationRole) GetDestination() *Destination {
	if m != nil {
		return m.Destination
	}
	return nil
}

type ReplicationConfiguration struct {
	Role                 string             `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Rules                []*ReplicationRole `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ReplicationConfiguration) Reset()         { *m = ReplicationConfiguration{} }
func (m *ReplicationConfiguration) String() string { return proto.CompactTextString(m) }
func (*ReplicationConfiguration) ProtoMessage()    {}
func (*ReplicationConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{11}
}
func (m *ReplicationConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicationConfiguration.Unmarshal(m, b)
}
func (m *ReplicationConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicationConfiguration.Marshal(b, m, deterministic)
}
func (dst *ReplicationConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationConfiguration.Merge(dst, src)
}
func (m *ReplicationConfiguration) XXX_Size() int {
	return xxx_messageInfo_ReplicationConfiguration.Size(m)
}
func (m *ReplicationConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationConfiguration proto.InternalMessageInfo

func (m *ReplicationConfiguration) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *ReplicationConfiguration) GetRules() []*ReplicationRole {
	if m != nil {
		return m.Rules
	}
	return nil
}

type Tag struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val                  string   `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{12}
}
func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (dst *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(dst, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Tag) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

type LifecycleFilter struct {
	Prefix               string   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Tags                 []*Tag   `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LifecycleFilter) Reset()         { *m = LifecycleFilter{} }
func (m *LifecycleFilter) String() string { return proto.CompactTextString(m) }
func (*LifecycleFilter) ProtoMessage()    {}
func (*LifecycleFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{13}
}
func (m *LifecycleFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LifecycleFilter.Unmarshal(m, b)
}
func (m *LifecycleFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LifecycleFilter.Marshal(b, m, deterministic)
}
func (dst *LifecycleFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LifecycleFilter.Merge(dst, src)
}
func (m *LifecycleFilter) XXX_Size() int {
	return xxx_messageInfo_LifecycleFilter.Size(m)
}
func (m *LifecycleFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_LifecycleFilter.DiscardUnknown(m)
}

var xxx_messageInfo_LifecycleFilter proto.InternalMessageInfo

func (m *LifecycleFilter) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *LifecycleFilter) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Action struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Days                 int32    `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`
	DeleteMarker         string   `protobuf:"bytes,4,opt,name=deleteMarker,proto3" json:"deleteMarker,omitempty"`
	Tier                 int32    `protobuf:"varint,5,opt,name=tier,proto3" json:"tier,omitempty"`
	Backend              string   `protobuf:"bytes,6,opt,name=backend,proto3" json:"backend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{14}
}
func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (dst *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(dst, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Action) GetDays() int32 {
	if m != nil {
		return m.Days
	}
	return 0
}

func (m *Action) GetDeleteMarker() string {
	if m != nil {
		return m.DeleteMarker
	}
	return ""
}

func (m *Action) GetTier() int32 {
	if m != nil {
		return m.Tier
	}
	return 0
}

func (m *Action) GetBackend() string {
	if m != nil {
		return m.Backend
	}
	return ""
}

type LifecycleRule struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string           `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Filter               *LifecycleFilter `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Actions              []*Action        `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LifecycleRule) Reset()         { *m = LifecycleRule{} }
func (m *LifecycleRule) String() string { return proto.CompactTextString(m) }
func (*LifecycleRule) ProtoMessage()    {}
func (*LifecycleRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{15}
}
func (m *LifecycleRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LifecycleRule.Unmarshal(m, b)
}
func (m *LifecycleRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LifecycleRule.Marshal(b, m, deterministic)
}
func (dst *LifecycleRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LifecycleRule.Merge(dst, src)
}
func (m *LifecycleRule) XXX_Size() int {
	return xxx_messageInfo_LifecycleRule.Size(m)
}
func (m *LifecycleRule) XXX_DiscardUnknown() {
	xxx_messageInfo_LifecycleRule.DiscardUnknown(m)
}

var xxx_messageInfo_LifecycleRule proto.InternalMessageInfo

func (m *LifecycleRule) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LifecycleRule) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *LifecycleRule) GetFilter() *LifecycleFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *LifecycleRule) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

type ReplicationInfo struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Backend              string   `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	StorageClass         string   `protobuf:"bytes,3,opt,name=storageClass,proto3" json:"storageClass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicationInfo) Reset()         { *m = ReplicationInfo{} }
func (m *ReplicationInfo) String() string { return proto.CompactTextString(m) }
func (*ReplicationInfo) ProtoMessage()    {}
func (*ReplicationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{16}
}
func (m *ReplicationInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicationInfo.Unmarshal(m, b)
}
func (m *ReplicationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicationInfo.Marshal(b, m, deterministic)
}
func (dst *ReplicationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationInfo.Merge(dst, src)
}
func (m *ReplicationInfo) XXX_Size() int {
	return xxx_messageInfo_ReplicationInfo.Size(m)
}
func (m *ReplicationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationInfo proto.InternalMessageInfo

func (m *ReplicationInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ReplicationInfo) GetBackend() string {
	if m != nil {
		return m.Backend
	}
	return ""
}

func (m *ReplicationInfo) GetStorageClass() string {
	if m != nil {
		return m.StorageClass
	}
	return ""
}

type Bucket struct {
	Name                     string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner                    string                    `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	OwnerDisplayName         string                    `protobuf:"bytes,3,opt,name=ownerDisplayName,proto3" json:"ownerDisplayName,omitempty"`
	Acl                      *ACL                      `protobuf:"bytes,4,opt,name=acl,proto3" json:"acl,omitempty"`
	CreationDate             int64                     `protobuf:"varint,5,opt,name=creationDate,proto3" json:"creationDate,omitempty"`
	Transient                bool                      `protobuf:"varint,6,opt,name=transient,proto3" json:"transient,omitempty"`
	Deleted                  bool                      `protobuf:"varint,7,opt,name=deleted,proto3" json:"deleted,omitempty"`
	ServerSideEncryption     *ServerSideEncryption     `protobuf:"bytes,8,opt,name=serverSideEncryption,proto3" json:"serverSideEncryption,omitempty"`
	VersioningConfiguration  *VersioningConfiguration  `protobuf:"bytes,9,opt,name=versioningConfiguration,proto3" json:"versioningConfiguration,omitempty"`
	Backend                  string                    `protobuf:"bytes,10,opt,name=backend,proto3" json:"backend,omitempty"`
	WebsiteConfiguration     *WebsiteConfiguration     `protobuf:"bytes,11,opt,name=websiteConfiguration,proto3" json:"websiteConfiguration,omitempty"`
	Cors                     *CORSConfiguration        `protobuf:"bytes,12,opt,name=cors,proto3" json:"cors,omitempty"`
	ReplicationConfiguration *ReplicationConfiguration `protobuf:"bytes,13,opt,name=replicationConfiguration,proto3" json:"replicationConfiguration,omitempty"`
	// string storageClass = 14;
	LifecycleConfiguration []*LifecycleRule `protobuf:"bytes,14,rep,name=lifecycleConfiguration,proto3" json:"lifecycleConfiguration,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}         `json:"-"`
	XXX_unrecognized       []byte           `json:"-"`
	XXX_sizecache          int32            `json:"-"`
}

func (m *Bucket) Reset()         { *m = Bucket{} }
func (m *Bucket) String() string { return proto.CompactTextString(m) }
func (*Bucket) ProtoMessage()    {}
func (*Bucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{17}
}
func (m *Bucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucket.Unmarshal(m, b)
}
func (m *Bucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucket.Marshal(b, m, deterministic)
}
func (dst *Bucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucket.Merge(dst, src)
}
func (m *Bucket) XXX_Size() int {
	return xxx_messageInfo_Bucket.Size(m)
}
func (m *Bucket) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucket.DiscardUnknown(m)
}

var xxx_messageInfo_Bucket proto.InternalMessageInfo

func (m *Bucket) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Bucket) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Bucket) GetOwnerDisplayName() string {
	if m != nil {
		return m.OwnerDisplayName
	}
	return ""
}

func (m *Bucket) GetAcl() *ACL {
	if m != nil {
		return m.Acl
	}
	return nil
}

func (m *Bucket) GetCreationDate() int64 {
	if m != nil {
		return m.CreationDate
	}
	return 0
}

func (m *Bucket) GetTransient() bool {
	if m != nil {
		return m.Transient
	}
	return false
}

func (m *Bucket) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *Bucket) GetServerSideEncryption() *ServerSideEncryption {
	if m != nil {
		return m.ServerSideEncryption
	}
	return nil
}

func (m *Bucket) GetVersioningConfiguration() *VersioningConfiguration {
	if m != nil {
		return m.VersioningConfiguration
	}
	return nil
}

func (m *Bucket) GetBackend() string {
	if m != nil {
		return m.Backend
	}
	return ""
}

func (m *Bucket) GetWebsiteConfiguration() *WebsiteConfiguration {
	if m != nil {
		return m.WebsiteConfiguration
	}
	return nil
}

func (m *Bucket) GetCors() *CORSConfiguration {
	if m != nil {
		return m.Cors
	}
	return nil
}

func (m *Bucket) GetReplicationConfiguration() *ReplicationConfiguration {
	if m != nil {
		return m.ReplicationConfiguration
	}
	return nil
}

func (m *Bucket) GetLifecycleConfiguration() []*LifecycleRule {
	if m != nil {
		return m.LifecycleConfiguration
	}
	return nil
}

type Partion struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	PartNumber           string   `protobuf:"bytes,2,opt,name=partNumber,proto3" json:"partNumber,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Etag                 string   `protobuf:"bytes,4,opt,name=etag,proto3" json:"etag,omitempty"`
	LastModified         int64    `protobuf:"varint,5,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Partion) Reset()         { *m = Partion{} }
func (m *Partion) String() string { return proto.CompactTextString(m) }
func (*Partion) ProtoMessage()    {}
func (*Partion) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{18}
}
func (m *Partion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partion.Unmarshal(m, b)
}
func (m *Partion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partion.Marshal(b, m, deterministic)
}
func (dst *Partion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partion.Merge(dst, src)
}
func (m *Partion) XXX_Size() int {
	return xxx_messageInfo_Partion.Size(m)
}
func (m *Partion) XXX_DiscardUnknown() {
	xxx_messageInfo_Partion.DiscardUnknown(m)
}

var xxx_messageInfo_Partion proto.InternalMessageInfo

func (m *Partion) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Partion) GetPartNumber() string {
	if m != nil {
		return m.PartNumber
	}
	return ""
}

func (m *Partion) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Partion) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *Partion) GetLastModified() int64 {
	if m != nil {
		return m.LastModified
	}
	return 0
}

type Version struct {
	Versionid            string   `protobuf:"bytes,1,opt,name=versionid,proto3" json:"versionid,omitempty"`
	Etag                 string   `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	IsLatest             string   `protobuf:"bytes,3,opt,name=isLatest,proto3" json:"isLatest,omitempty"`
	LastModified         int64    `protobuf:"varint,4,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
	Size                 int64    `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{19}
}
func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (dst *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(dst, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetVersionid() string {
	if m != nil {
		return m.Versionid
	}
	return ""
}

func (m *Version) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *Version) GetIsLatest() string {
	if m != nil {
		return m.IsLatest
	}
	return ""
}

func (m *Version) GetLastModified() int64 {
	if m != nil {
		return m.LastModified
	}
	return 0
}

func (m *Version) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Object struct {
	ObjectKey               string                `protobuf:"bytes,1,opt,name=objectKey,proto3" json:"objectKey,omitempty"`
	BucketName              string                `protobuf:"bytes,2,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	Owner                   string                `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	OwnerDisplayName        string                `protobuf:"bytes,4,opt,name=ownerDisplayName,proto3" json:"ownerDisplayName,omitempty"`
	CacheControl            string                `protobuf:"bytes,5,opt,name=cacheControl,proto3" json:"cacheControl,omitempty"`
	ContentDisposition      string                `protobuf:"bytes,6,opt,name=contentDisposition,proto3" json:"contentDisposition,omitempty"`
	ContentEncoding         string                `protobuf:"bytes,7,opt,name=contentEncoding,proto3" json:"contentEncoding,omitempty"`
	Expires                 string                `protobuf:"bytes,8,opt,name=expires,proto3" json:"expires,omitempty"`
	ContentLength           string                `protobuf:"bytes,9,opt,name=contentLength,proto3" json:"contentLength,omitempty"`
	ContentType             string                `protobuf:"bytes,10,opt,name=contentType,proto3" json:"contentType,omitempty"`
	ContentMd5              string                `protobuf:"bytes,11,opt,name=contentMd5,proto3" json:"contentMd5,omitempty"`
	Versions                []*Version            `protobuf:"bytes,12,rep,name=versions,proto3" json:"versions,omitempty"`
	StorageClass            string                `protobuf:"bytes,13,opt,name=storageClass,proto3" json:"storageClass,omitempty"`
	ServerSideEncryption    *ServerSideEncryption `protobuf:"bytes,14,opt,name=serverSideEncryption,proto3" json:"serverSideEncryption,omitempty"`
	WebsiteRedirectLocation string                `protobuf:"bytes,15,opt,name=websiteRedirectLocation,proto3" json:"websiteRedirectLocation,omitempty"`
	Acl                     *ACL                  `protobuf:"bytes,16,opt,name=acl,proto3" json:"acl,omitempty"`
	Backend                 string                `protobuf:"bytes,17,opt,name=backend,proto3" json:"backend,omitempty"`
	IsNull                  string                `protobuf:"bytes,18,opt,name=isNull,proto3" json:"isNull,omitempty"`
	IsDeleteMarker          string                `protobuf:"bytes,19,opt,name=isDeleteMarker,proto3" json:"isDeleteMarker,omitempty"`
	ReplicationInfo         []*ReplicationInfo    `protobuf:"bytes,20,rep,name=replicationInfo,proto3" json:"replicationInfo,omitempty"`
	Size                    int64                 `protobuf:"varint,21,opt,name=size,proto3" json:"size,omitempty"`
	Partions                []*Partion            `protobuf:"bytes,22,rep,name=partions,proto3" json:"partions,omitempty"`
	Tags                    []*Tag                `protobuf:"bytes,23,rep,name=tags,proto3" json:"tags,omitempty"`
	LastModified            int64                 `protobuf:"varint,24,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
	InitFlag                string                `protobuf:"bytes,25,opt,name=initFlag,proto3" json:"initFlag,omitempty"`
	ETag                    string                `protobuf:"bytes,26,opt,name=ETag,proto3" json:"ETag,omitempty"`
	Tier                    int32                 `protobuf:"varint,27,opt,name=tier,proto3" json:"tier,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}              `json:"-"`
	XXX_unrecognized        []byte                `json:"-"`
	XXX_sizecache           int32                 `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{20}
}
func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (dst *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(dst, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetObjectKey() string {
	if m != nil {
		return m.ObjectKey
	}
	return ""
}

func (m *Object) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *Object) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Object) GetOwnerDisplayName() string {
	if m != nil {
		return m.OwnerDisplayName
	}
	return ""
}

func (m *Object) GetCacheControl() string {
	if m != nil {
		return m.CacheControl
	}
	return ""
}

func (m *Object) GetContentDisposition() string {
	if m != nil {
		return m.ContentDisposition
	}
	return ""
}

func (m *Object) GetContentEncoding() string {
	if m != nil {
		return m.ContentEncoding
	}
	return ""
}

func (m *Object) GetExpires() string {
	if m != nil {
		return m.Expires
	}
	return ""
}

func (m *Object) GetContentLength() string {
	if m != nil {
		return m.ContentLength
	}
	return ""
}

func (m *Object) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Object) GetContentMd5() string {
	if m != nil {
		return m.ContentMd5
	}
	return ""
}

func (m *Object) GetVersions() []*Version {
	if m != nil {
		return m.Versions
	}
	return nil
}

func (m *Object) GetStorageClass() string {
	if m != nil {
		return m.StorageClass
	}
	return ""
}

func (m *Object) GetServerSideEncryption() *ServerSideEncryption {
	if m != nil {
		return m.ServerSideEncryption
	}
	return nil
}

func (m *Object) GetWebsiteRedirectLocation() string {
	if m != nil {
		return m.WebsiteRedirectLocation
	}
	return ""
}

func (m *Object) GetAcl() *ACL {
	if m != nil {
		return m.Acl
	}
	return nil
}

func (m *Object) GetBackend() string {
	if m != nil {
		return m.Backend
	}
	return ""
}

func (m *Object) GetIsNull() string {
	if m != nil {
		return m.IsNull
	}
	return ""
}

func (m *Object) GetIsDeleteMarker() string {
	if m != nil {
		return m.IsDeleteMarker
	}
	return ""
}

func (m *Object) GetReplicationInfo() []*ReplicationInfo {
	if m != nil {
		return m.ReplicationInfo
	}
	return nil
}

func (m *Object) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Object) GetPartions() []*Partion {
	if m != nil {
		return m.Partions
	}
	return nil
}

func (m *Object) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Object) GetLastModified() int64 {
	if m != nil {
		return m.LastModified
	}
	return 0
}

func (m *Object) GetInitFlag() string {
	if m != nil {
		return m.InitFlag
	}
	return ""
}

func (m *Object) GetETag() string {
	if m != nil {
		return m.ETag
	}
	return ""
}

func (m *Object) GetTier() int32 {
	if m != nil {
		return m.Tier
	}
	return 0
}

type ListBucketsResponse struct {
	Buckets              []*Bucket `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListBucketsResponse) Reset()         { *m = ListBucketsResponse{} }
func (m *ListBucketsResponse) String() string { return proto.CompactTextString(m) }
func (*ListBucketsResponse) ProtoMessage()    {}
func (*ListBucketsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{21}
}
func (m *ListBucketsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBucketsResponse.Unmarshal(m, b)
}
func (m *ListBucketsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBucketsResponse.Marshal(b, m, deterministic)
}
func (dst *ListBucketsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBucketsResponse.Merge(dst, src)
}
func (m *ListBucketsResponse) XXX_Size() int {
	return xxx_messageInfo_ListBucketsResponse.Size(m)
}
func (m *ListBucketsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBucketsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBucketsResponse proto.InternalMessageInfo

func (m *ListBucketsResponse) GetBuckets() []*Bucket {
	if m != nil {
		return m.Buckets
	}
	return nil
}

type BaseResponse struct {
	ErrorCode            string   `protobuf:"bytes,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseResponse) Reset()         { *m = BaseResponse{} }
func (m *BaseResponse) String() string { return proto.CompactTextString(m) }
func (*BaseResponse) ProtoMessage()    {}
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{22}
}
func (m *BaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResponse.Unmarshal(m, b)
}
func (m *BaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResponse.Marshal(b, m, deterministic)
}
func (dst *BaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResponse.Merge(dst, src)
}
func (m *BaseResponse) XXX_Size() int {
	return xxx_messageInfo_BaseResponse.Size(m)
}
func (m *BaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResponse proto.InternalMessageInfo

func (m *BaseResponse) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *BaseResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type BaseRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseRequest) Reset()         { *m = BaseRequest{} }
func (m *BaseRequest) String() string { return proto.CompactTextString(m) }
func (*BaseRequest) ProtoMessage()    {}
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{23}
}
func (m *BaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseRequest.Unmarshal(m, b)
}
func (m *BaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseRequest.Marshal(b, m, deterministic)
}
func (dst *BaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseRequest.Merge(dst, src)
}
func (m *BaseRequest) XXX_Size() int {
	return xxx_messageInfo_BaseRequest.Size(m)
}
func (m *BaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BaseRequest proto.InternalMessageInfo

func (m *BaseRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListObjectsRequest struct {
	// Bucket is a required field
	Bucket               string            `protobuf:"bytes,1,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Delimiter            string            `protobuf:"bytes,2,opt,name=Delimiter,proto3" json:"Delimiter,omitempty"`
	Owner                string            `protobuf:"bytes,3,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Filter               map[string]string `protobuf:"bytes,4,rep,name=Filter,proto3" json:"Filter,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListObjectsRequest) Reset()         { *m = ListObjectsRequest{} }
func (m *ListObjectsRequest) String() string { return proto.CompactTextString(m) }
func (*ListObjectsRequest) ProtoMessage()    {}
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{24}
}
func (m *ListObjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListObjectsRequest.Unmarshal(m, b)
}
func (m *ListObjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListObjectsRequest.Marshal(b, m, deterministic)
}
func (dst *ListObjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListObjectsRequest.Merge(dst, src)
}
func (m *ListObjectsRequest) XXX_Size() int {
	return xxx_messageInfo_ListObjectsRequest.Size(m)
}
func (m *ListObjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListObjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListObjectsRequest proto.InternalMessageInfo

func (m *ListObjectsRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ListObjectsRequest) GetDelimiter() string {
	if m != nil {
		return m.Delimiter
	}
	return ""
}

func (m *ListObjectsRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ListObjectsRequest) GetFilter() map[string]string {
	if m != nil {
		return m.Filter
	}
	return nil
}

type ListObjectResponse struct {
	ListObjects          []*Object `protobuf:"bytes,1,rep,name=ListObjects,proto3" json:"ListObjects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListObjectResponse) Reset()         { *m = ListObjectResponse{} }
func (m *ListObjectResponse) String() string { return proto.CompactTextString(m) }
func (*ListObjectResponse) ProtoMessage()    {}
func (*ListObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{25}
}
func (m *ListObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListObjectResponse.Unmarshal(m, b)
}
func (m *ListObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListObjectResponse.Marshal(b, m, deterministic)
}
func (dst *ListObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListObjectResponse.Merge(dst, src)
}
func (m *ListObjectResponse) XXX_Size() int {
	return xxx_messageInfo_ListObjectResponse.Size(m)
}
func (m *ListObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListObjectResponse proto.InternalMessageInfo

func (m *ListObjectResponse) GetListObjects() []*Object {
	if m != nil {
		return m.ListObjects
	}
	return nil
}

type DeleteObjectInput struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Versionid            string   `protobuf:"bytes,3,opt,name=Versionid,proto3" json:"Versionid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteObjectInput) Reset()         { *m = DeleteObjectInput{} }
func (m *DeleteObjectInput) String() string { return proto.CompactTextString(m) }
func (*DeleteObjectInput) ProtoMessage()    {}
func (*DeleteObjectInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{26}
}
func (m *DeleteObjectInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteObjectInput.Unmarshal(m, b)
}
func (m *DeleteObjectInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteObjectInput.Marshal(b, m, deterministic)
}
func (dst *DeleteObjectInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteObjectInput.Merge(dst, src)
}
func (m *DeleteObjectInput) XXX_Size() int {
	return xxx_messageInfo_DeleteObjectInput.Size(m)
}
func (m *DeleteObjectInput) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteObjectInput.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteObjectInput proto.InternalMessageInfo

func (m *DeleteObjectInput) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *DeleteObjectInput) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DeleteObjectInput) GetVersionid() string {
	if m != nil {
		return m.Versionid
	}
	return ""
}

type GetObjectInput struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Versionid            string   `protobuf:"bytes,3,opt,name=Versionid,proto3" json:"Versionid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectInput) Reset()         { *m = GetObjectInput{} }
func (m *GetObjectInput) String() string { return proto.CompactTextString(m) }
func (*GetObjectInput) ProtoMessage()    {}
func (*GetObjectInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{27}
}
func (m *GetObjectInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectInput.Unmarshal(m, b)
}
func (m *GetObjectInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectInput.Marshal(b, m, deterministic)
}
func (dst *GetObjectInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectInput.Merge(dst, src)
}
func (m *GetObjectInput) XXX_Size() int {
	return xxx_messageInfo_GetObjectInput.Size(m)
}
func (m *GetObjectInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectInput proto.InternalMessageInfo

func (m *GetObjectInput) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *GetObjectInput) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetObjectInput) GetVersionid() string {
	if m != nil {
		return m.Versionid
	}
	return ""
}

type MultipartUpload struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	UploadId             string   `protobuf:"bytes,3,opt,name=uploadId,proto3" json:"uploadId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultipartUpload) Reset()         { *m = MultipartUpload{} }
func (m *MultipartUpload) String() string { return proto.CompactTextString(m) }
func (*MultipartUpload) ProtoMessage()    {}
func (*MultipartUpload) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{28}
}
func (m *MultipartUpload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultipartUpload.Unmarshal(m, b)
}
func (m *MultipartUpload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultipartUpload.Marshal(b, m, deterministic)
}
func (dst *MultipartUpload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultipartUpload.Merge(dst, src)
}
func (m *MultipartUpload) XXX_Size() int {
	return xxx_messageInfo_MultipartUpload.Size(m)
}
func (m *MultipartUpload) XXX_DiscardUnknown() {
	xxx_messageInfo_MultipartUpload.DiscardUnknown(m)
}

var xxx_messageInfo_MultipartUpload proto.InternalMessageInfo

func (m *MultipartUpload) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *MultipartUpload) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MultipartUpload) GetUploadId() string {
	if m != nil {
		return m.UploadId
	}
	return ""
}

type ListParts struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	UploadId             string   `protobuf:"bytes,3,opt,name=uploadId,proto3" json:"uploadId,omitempty"`
	MaxParts             int64    `protobuf:"varint,4,opt,name=MaxParts,proto3" json:"MaxParts,omitempty"`
	PartNumberMarker     int64    `protobuf:"varint,5,opt,name=PartNumberMarker,proto3" json:"PartNumberMarker,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListParts) Reset()         { *m = ListParts{} }
func (m *ListParts) String() string { return proto.CompactTextString(m) }
func (*ListParts) ProtoMessage()    {}
func (*ListParts) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{29}
}
func (m *ListParts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListParts.Unmarshal(m, b)
}
func (m *ListParts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListParts.Marshal(b, m, deterministic)
}
func (dst *ListParts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListParts.Merge(dst, src)
}
func (m *ListParts) XXX_Size() int {
	return xxx_messageInfo_ListParts.Size(m)
}
func (m *ListParts) XXX_DiscardUnknown() {
	xxx_messageInfo_ListParts.DiscardUnknown(m)
}

var xxx_messageInfo_ListParts proto.InternalMessageInfo

func (m *ListParts) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ListParts) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ListParts) GetUploadId() string {
	if m != nil {
		return m.UploadId
	}
	return ""
}

func (m *ListParts) GetMaxParts() int64 {
	if m != nil {
		return m.MaxParts
	}
	return 0
}

func (m *ListParts) GetPartNumberMarker() int64 {
	if m != nil {
		return m.PartNumberMarker
	}
	return 0
}

type TList struct {
	Tier                 []int32  `protobuf:"varint,1,rep,packed,name=Tier,proto3" json:"Tier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TList) Reset()         { *m = TList{} }
func (m *TList) String() string { return proto.CompactTextString(m) }
func (*TList) ProtoMessage()    {}
func (*TList) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{30}
}
func (m *TList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TList.Unmarshal(m, b)
}
func (m *TList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TList.Marshal(b, m, deterministic)
}
func (dst *TList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TList.Merge(dst, src)
}
func (m *TList) XXX_Size() int {
	return xxx_messageInfo_TList.Size(m)
}
func (m *TList) XXX_DiscardUnknown() {
	xxx_messageInfo_TList.DiscardUnknown(m)
}

var xxx_messageInfo_TList proto.InternalMessageInfo

func (m *TList) GetTier() []int32 {
	if m != nil {
		return m.Tier
	}
	return nil
}

type Tier2ClassName struct {
	Lst                  map[int32]string `protobuf:"bytes,1,rep,name=lst,proto3" json:"lst,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Tier2ClassName) Reset()         { *m = Tier2ClassName{} }
func (m *Tier2ClassName) String() string { return proto.CompactTextString(m) }
func (*Tier2ClassName) ProtoMessage()    {}
func (*Tier2ClassName) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{31}
}
func (m *Tier2ClassName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tier2ClassName.Unmarshal(m, b)
}
func (m *Tier2ClassName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tier2ClassName.Marshal(b, m, deterministic)
}
func (dst *Tier2ClassName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tier2ClassName.Merge(dst, src)
}
func (m *Tier2ClassName) XXX_Size() int {
	return xxx_messageInfo_Tier2ClassName.Size(m)
}
func (m *Tier2ClassName) XXX_DiscardUnknown() {
	xxx_messageInfo_Tier2ClassName.DiscardUnknown(m)
}

var xxx_messageInfo_Tier2ClassName proto.InternalMessageInfo

func (m *Tier2ClassName) GetLst() map[int32]string {
	if m != nil {
		return m.Lst
	}
	return nil
}

type GetTierMapResponse struct {
	TransitionMap        map[int32]*TList           `protobuf:"bytes,1,rep,name=TransitionMap,proto3" json:"TransitionMap,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Tier2Name            map[string]*Tier2ClassName `protobuf:"bytes,2,rep,name=Tier2Name,proto3" json:"Tier2Name,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetTierMapResponse) Reset()         { *m = GetTierMapResponse{} }
func (m *GetTierMapResponse) String() string { return proto.CompactTextString(m) }
func (*GetTierMapResponse) ProtoMessage()    {}
func (*GetTierMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{32}
}
func (m *GetTierMapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTierMapResponse.Unmarshal(m, b)
}
func (m *GetTierMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTierMapResponse.Marshal(b, m, deterministic)
}
func (dst *GetTierMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTierMapResponse.Merge(dst, src)
}
func (m *GetTierMapResponse) XXX_Size() int {
	return xxx_messageInfo_GetTierMapResponse.Size(m)
}
func (m *GetTierMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTierMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTierMapResponse proto.InternalMessageInfo

func (m *GetTierMapResponse) GetTransitionMap() map[int32]*TList {
	if m != nil {
		return m.TransitionMap
	}
	return nil
}

func (m *GetTierMapResponse) GetTier2Name() map[string]*Tier2ClassName {
	if m != nil {
		return m.Tier2Name
	}
	return nil
}

type UpdateObjMetaRequest struct {
	ObjKey               string            `protobuf:"bytes,1,opt,name=ObjKey,proto3" json:"ObjKey,omitempty"`
	BucketName           string            `protobuf:"bytes,2,opt,name=BucketName,proto3" json:"BucketName,omitempty"`
	Setting              map[string]string `protobuf:"bytes,3,rep,name=Setting,proto3" json:"Setting,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateObjMetaRequest) Reset()         { *m = UpdateObjMetaRequest{} }
func (m *UpdateObjMetaRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateObjMetaRequest) ProtoMessage()    {}
func (*UpdateObjMetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{33}
}
func (m *UpdateObjMetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateObjMetaRequest.Unmarshal(m, b)
}
func (m *UpdateObjMetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateObjMetaRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateObjMetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateObjMetaRequest.Merge(dst, src)
}
func (m *UpdateObjMetaRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateObjMetaRequest.Size(m)
}
func (m *UpdateObjMetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateObjMetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateObjMetaRequest proto.InternalMessageInfo

func (m *UpdateObjMetaRequest) GetObjKey() string {
	if m != nil {
		return m.ObjKey
	}
	return ""
}

func (m *UpdateObjMetaRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *UpdateObjMetaRequest) GetSetting() map[string]string {
	if m != nil {
		return m.Setting
	}
	return nil
}

type StorageClass struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Tier                 int32    `protobuf:"varint,2,opt,name=Tier,proto3" json:"Tier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageClass) Reset()         { *m = StorageClass{} }
func (m *StorageClass) String() string { return proto.CompactTextString(m) }
func (*StorageClass) ProtoMessage()    {}
func (*StorageClass) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{34}
}
func (m *StorageClass) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageClass.Unmarshal(m, b)
}
func (m *StorageClass) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageClass.Marshal(b, m, deterministic)
}
func (dst *StorageClass) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageClass.Merge(dst, src)
}
func (m *StorageClass) XXX_Size() int {
	return xxx_messageInfo_StorageClass.Size(m)
}
func (m *StorageClass) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageClass.DiscardUnknown(m)
}

var xxx_messageInfo_StorageClass proto.InternalMessageInfo

func (m *StorageClass) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StorageClass) GetTier() int32 {
	if m != nil {
		return m.Tier
	}
	return 0
}

type GetStorageClassesResponse struct {
	Classes              []*StorageClass `protobuf:"bytes,1,rep,name=classes,proto3" json:"classes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetStorageClassesResponse) Reset()         { *m = GetStorageClassesResponse{} }
func (m *GetStorageClassesResponse) String() string { return proto.CompactTextString(m) }
func (*GetStorageClassesResponse) ProtoMessage()    {}
func (*GetStorageClassesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_s3_2d0f79dcfc8a0608, []int{35}
}
func (m *GetStorageClassesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStorageClassesResponse.Unmarshal(m, b)
}
func (m *GetStorageClassesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStorageClassesResponse.Marshal(b, m, deterministic)
}
func (dst *GetStorageClassesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStorageClassesResponse.Merge(dst, src)
}
func (m *GetStorageClassesResponse) XXX_Size() int {
	return xxx_messageInfo_GetStorageClassesResponse.Size(m)
}
func (m *GetStorageClassesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStorageClassesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStorageClassesResponse proto.InternalMessageInfo

func (m *GetStorageClassesResponse) GetClasses() []*StorageClass {
	if m != nil {
		return m.Classes
	}
	return nil
}

func init() {
	proto.RegisterType((*ACL)(nil), "ACL")
	proto.RegisterType((*ServerSideEncryption)(nil), "ServerSideEncryption")
	proto.RegisterType((*VersioningConfiguration)(nil), "VersioningConfiguration")
	proto.RegisterType((*RedirectAllRequestsTo)(nil), "RedirectAllRequestsTo")
	proto.RegisterType((*Redirect)(nil), "Redirect")
	proto.RegisterType((*Condition)(nil), "Condition")
	proto.RegisterType((*RoutingRules)(nil), "RoutingRules")
	proto.RegisterType((*WebsiteConfiguration)(nil), "WebsiteConfiguration")
	proto.RegisterType((*CORSConfiguration)(nil), "CORSConfiguration")
	proto.RegisterType((*Destination)(nil), "Destination")
	proto.RegisterType((*ReplicationRole)(nil), "ReplicationRole")
	proto.RegisterType((*ReplicationConfiguration)(nil), "ReplicationConfiguration")
	proto.RegisterType((*Tag)(nil), "Tag")
	proto.RegisterType((*LifecycleFilter)(nil), "LifecycleFilter")
	proto.RegisterType((*Action)(nil), "Action")
	proto.RegisterType((*LifecycleRule)(nil), "LifecycleRule")
	proto.RegisterType((*ReplicationInfo)(nil), "ReplicationInfo")
	proto.RegisterType((*Bucket)(nil), "Bucket")
	proto.RegisterType((*Partion)(nil), "Partion")
	proto.RegisterType((*Version)(nil), "Version")
	proto.RegisterType((*Object)(nil), "Object")
	proto.RegisterType((*ListBucketsResponse)(nil), "ListBucketsResponse")
	proto.RegisterType((*BaseResponse)(nil), "BaseResponse")
	proto.RegisterType((*BaseRequest)(nil), "BaseRequest")
	proto.RegisterType((*ListObjectsRequest)(nil), "ListObjectsRequest")
	proto.RegisterMapType((map[string]string)(nil), "ListObjectsRequest.FilterEntry")
	proto.RegisterType((*ListObjectResponse)(nil), "ListObjectResponse")
	proto.RegisterType((*DeleteObjectInput)(nil), "DeleteObjectInput")
	proto.RegisterType((*GetObjectInput)(nil), "GetObjectInput")
	proto.RegisterType((*MultipartUpload)(nil), "MultipartUpload")
	proto.RegisterType((*ListParts)(nil), "ListParts")
	proto.RegisterType((*TList)(nil), "TList")
	proto.RegisterType((*Tier2ClassName)(nil), "Tier2ClassName")
	proto.RegisterMapType((map[int32]string)(nil), "Tier2ClassName.LstEntry")
	proto.RegisterType((*GetTierMapResponse)(nil), "GetTierMapResponse")
	proto.RegisterMapType((map[string]*Tier2ClassName)(nil), "GetTierMapResponse.Tier2NameEntry")
	proto.RegisterMapType((map[int32]*TList)(nil), "GetTierMapResponse.TransitionMapEntry")
	proto.RegisterType((*UpdateObjMetaRequest)(nil), "UpdateObjMetaRequest")
	proto.RegisterMapType((map[string]string)(nil), "UpdateObjMetaRequest.SettingEntry")
	proto.RegisterType((*StorageClass)(nil), "StorageClass")
	proto.RegisterType((*GetStorageClassesResponse)(nil), "GetStorageClassesResponse")
}

func init() { proto.RegisterFile("s3.proto", fileDescriptor_s3_2d0f79dcfc8a0608) }

var fileDescriptor_s3_2d0f79dcfc8a0608 = []byte{
	// 2217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xcd, 0x6f, 0x1b, 0xc7,
	0x15, 0x37, 0x3f, 0x45, 0x3e, 0x52, 0x1f, 0x1e, 0xd3, 0xf2, 0x9a, 0x56, 0x1b, 0x67, 0xe1, 0x38,
	0x4a, 0x0e, 0x0b, 0x44, 0x46, 0x13, 0xc7, 0x28, 0x9a, 0xc8, 0x94, 0xec, 0x08, 0x26, 0x2d, 0x61,
	0x44, 0xdb, 0x05, 0x7a, 0x30, 0x46, 0xbb, 0x23, 0x6a, 0xe3, 0xd5, 0x2e, 0xb3, 0x33, 0xb4, 0xc5,
	0x1e, 0xdb, 0x02, 0x3d, 0xf6, 0xd2, 0x4b, 0x0f, 0xbd, 0xf4, 0xff, 0xe8, 0xa1, 0xb7, 0xa0, 0xe7,
	0xfe, 0x07, 0x3d, 0xf5, 0xbf, 0x28, 0xe6, 0x6b, 0x39, 0xcb, 0x5d, 0xc6, 0x30, 0xd0, 0x9e, 0x38,
	0xef, 0x37, 0x6f, 0xde, 0xbc, 0xf7, 0xe6, 0x7d, 0x2d, 0xa1, 0xc5, 0x1e, 0x78, 0xd3, 0x34, 0xe1,
	0x89, 0xfb, 0xb7, 0x0a, 0xd4, 0xf6, 0x07, 0x43, 0xb4, 0x0d, 0x4d, 0x9f, 0xc4, 0x31, 0x0d, 0x9c,
	0xca, 0xdd, 0xca, 0x6e, 0x1b, 0x6b, 0x0a, 0x7d, 0x0c, 0xdd, 0x27, 0x2f, 0x86, 0xc3, 0xd7, 0x83,
	0xe3, 0xe7, 0x63, 0x7c, 0x3c, 0x74, 0xaa, 0x77, 0x6b, 0xbb, 0x6d, 0xdc, 0x11, 0x98, 0x86, 0x50,
	0x0f, 0x1a, 0xaf, 0xf0, 0xd1, 0xf8, 0xd0, 0xa9, 0xc9, 0x3d, 0x45, 0xa0, 0x3b, 0xd0, 0x96, 0x8b,
	0xd7, 0xfb, 0x83, 0x13, 0xa7, 0x2e, 0x77, 0x5a, 0x12, 0xd8, 0x1f, 0x9c, 0x20, 0x04, 0x75, 0x7c,
	0xb8, 0x7f, 0xe0, 0x34, 0x24, 0x2e, 0xd7, 0xe8, 0x36, 0xb4, 0xc4, 0xaf, 0xe4, 0x6f, 0x4a, 0x7c,
	0x4d, 0xd0, 0xfb, 0x83, 0x13, 0xf7, 0xcf, 0x15, 0xe8, 0x9d, 0xd2, 0xf4, 0x2d, 0x4d, 0x4f, 0xc3,
	0x80, 0x1e, 0xc6, 0x7e, 0x3a, 0x9f, 0xf2, 0x30, 0x89, 0xd1, 0x5d, 0xe8, 0xc8, 0xf5, 0xa9, 0x7f,
	0x41, 0x2f, 0xa9, 0x56, 0xdd, 0x86, 0xd0, 0x0e, 0xb4, 0x49, 0x34, 0x49, 0xd2, 0x90, 0x5f, 0x5c,
	0x3a, 0x55, 0xb9, 0xbf, 0x00, 0xc4, 0xf9, 0x4b, 0xc2, 0x38, 0x4d, 0x9f, 0xd1, 0xf9, 0x51, 0xe0,
	0xd4, 0xd4, 0x79, 0x0b, 0x42, 0x7d, 0x68, 0x5d, 0x92, 0x38, 0xe0, 0x49, 0x3a, 0x77, 0xea, 0x77,
	0x2b, 0xbb, 0x2d, 0x9c, 0xd1, 0xee, 0x31, 0xdc, 0x7a, 0x49, 0x53, 0x16, 0x26, 0x71, 0x18, 0x4f,
	0x06, 0x49, 0x7c, 0x1e, 0x4e, 0x66, 0x29, 0x91, 0x8a, 0x6d, 0x43, 0xf3, 0x94, 0x13, 0x3e, 0x63,
	0xc6, 0x9d, 0x8a, 0x12, 0xea, 0x8c, 0xce, 0xc9, 0x01, 0x8d, 0x28, 0xa7, 0x46, 0x9d, 0x0c, 0x70,
	0x8f, 0xe1, 0x26, 0xa6, 0x41, 0x98, 0x52, 0x9f, 0xef, 0x47, 0x11, 0xa6, 0x3f, 0xcc, 0x28, 0xe3,
	0x6c, 0x9c, 0x08, 0x2d, 0x2e, 0x12, 0xc6, 0x9f, 0x93, 0xcc, 0xc8, 0x8c, 0x16, 0x7b, 0xf2, 0x29,
	0xfd, 0x24, 0xd2, 0xaf, 0x93, 0xd1, 0xee, 0x3f, 0x2b, 0xd0, 0x32, 0x12, 0x73, 0x8c, 0x5a, 0x88,
	0xa1, 0x73, 0x17, 0x54, 0x97, 0x2e, 0xd8, 0x83, 0x5e, 0x4a, 0xa7, 0x11, 0xf1, 0xe9, 0x33, 0x3a,
	0x3f, 0x49, 0xe9, 0x79, 0x78, 0xf5, 0x2a, 0xe4, 0x17, 0xda, 0x5b, 0xa5, 0x7b, 0xe8, 0x3e, 0x6c,
	0x2c, 0x70, 0xc9, 0x5d, 0x97, 0xdc, 0x4b, 0x28, 0xfa, 0x1c, 0xb6, 0x2e, 0x38, 0x9f, 0x1a, 0x1d,
	0x07, 0x49, 0x40, 0x9d, 0x86, 0xe4, 0x2c, 0xe0, 0xee, 0x3b, 0x68, 0x0f, 0x92, 0x38, 0x08, 0xa5,
	0x83, 0x77, 0x61, 0xf3, 0x8d, 0xb9, 0xf1, 0xf0, 0x87, 0x19, 0x89, 0x8c, 0xa7, 0x97, 0x61, 0xf4,
	0x2d, 0xdc, 0x11, 0xa2, 0x0e, 0xd3, 0x34, 0x49, 0x85, 0x1c, 0x4c, 0xf9, 0x2c, 0x8d, 0x69, 0xa0,
	0x4f, 0x29, 0x6b, 0x7f, 0x8a, 0xc5, 0x7d, 0x0d, 0x5d, 0x9c, 0xcc, 0x78, 0x18, 0x4f, 0xf0, 0x2c,
	0xa2, 0x0c, 0x7d, 0x02, 0xad, 0x54, 0x2b, 0x26, 0x2f, 0xed, 0xec, 0xb5, 0x3d, 0xa3, 0x29, 0xce,
	0xb6, 0xd0, 0x2e, 0xb4, 0x7d, 0xa3, 0xaf, 0xbc, 0xa6, 0xb3, 0x07, 0x5e, 0x66, 0x01, 0x5e, 0x6c,
	0xba, 0xff, 0xae, 0x40, 0xef, 0x15, 0x3d, 0x63, 0x21, 0xa7, 0xf9, 0x30, 0xba, 0x07, 0xeb, 0x61,
	0x1c, 0xd0, 0xab, 0x83, 0xc4, 0x9f, 0x5d, 0xd2, 0x98, 0x6b, 0x1b, 0xf3, 0xa0, 0xe0, 0xa2, 0x42,
	0xf5, 0x8c, 0x4b, 0xd9, 0x94, 0x07, 0xd1, 0x10, 0x6e, 0xa6, 0x65, 0xc1, 0x25, 0xdf, 0xb1, 0xb3,
	0xb7, 0xed, 0x95, 0x86, 0x1e, 0x2e, 0x3f, 0x84, 0xbe, 0x80, 0x6e, 0x6a, 0xf9, 0x44, 0x66, 0x78,
	0x67, 0x6f, 0xdd, 0xb3, 0x1d, 0x85, 0x73, 0x2c, 0xee, 0x7f, 0x2a, 0x70, 0x7d, 0x70, 0x8c, 0x4f,
	0xf3, 0x26, 0x6e, 0x40, 0x35, 0x34, 0x45, 0xa7, 0x1a, 0x06, 0x22, 0x72, 0x48, 0x14, 0x25, 0xef,
	0x68, 0x30, 0xa2, 0xfc, 0x22, 0x09, 0xcc, 0x0b, 0x2d, 0xa1, 0x16, 0xdf, 0x71, 0x1a, 0x4e, 0xc2,
	0x98, 0xe9, 0x78, 0x5c, 0x42, 0x2d, 0xbe, 0xef, 0x28, 0x09, 0x68, 0xca, 0x4c, 0x24, 0xe6, 0x51,
	0xe1, 0xc4, 0x4b, 0x72, 0xb5, 0x3f, 0xa1, 0xa7, 0x54, 0x3c, 0x0c, 0xd3, 0x61, 0x98, 0x07, 0x85,
	0x34, 0x7a, 0x35, 0x4d, 0xd8, 0x42, 0x5a, 0x53, 0x49, 0xcb, 0xa3, 0xee, 0x11, 0x74, 0x0e, 0x28,
	0xe3, 0x61, 0x9c, 0x95, 0x83, 0xb3, 0x99, 0xff, 0x86, 0x9a, 0x07, 0xd4, 0x14, 0x72, 0xa1, 0xcb,
	0x78, 0x92, 0x92, 0x09, 0x1d, 0x44, 0x84, 0x19, 0x53, 0x73, 0x98, 0xfb, 0xfb, 0x0a, 0x6c, 0x62,
	0x3a, 0x8d, 0x42, 0x5f, 0xca, 0xc2, 0x49, 0x44, 0x0b, 0x4e, 0xdb, 0x86, 0xe6, 0x54, 0xc6, 0xbc,
	0x96, 0xa0, 0x29, 0xe4, 0xc0, 0x1a, 0x8d, 0xc9, 0x59, 0x44, 0x55, 0x6d, 0x6b, 0x61, 0x43, 0x22,
	0x0f, 0x3a, 0xc1, 0x42, 0x41, 0xe9, 0x93, 0xce, 0x5e, 0xd7, 0xb3, 0x94, 0xc6, 0x36, 0x83, 0xfb,
	0x12, 0x1c, 0x4b, 0x89, 0xfc, 0x13, 0x22, 0xa8, 0xa7, 0x49, 0x64, 0x2a, 0x93, 0x5c, 0xa3, 0xfb,
	0xd0, 0x48, 0x65, 0x60, 0x54, 0x65, 0x60, 0x6c, 0x79, 0x4b, 0x26, 0x60, 0xb5, 0xed, 0x7e, 0x06,
	0xb5, 0x31, 0x99, 0xa0, 0x2d, 0xa8, 0xbd, 0xa1, 0x73, 0x2d, 0x41, 0x2c, 0x05, 0xf2, 0x96, 0x44,
	0xda, 0x1e, 0xb1, 0x74, 0x07, 0xb0, 0x39, 0x0c, 0xcf, 0xa9, 0x3f, 0xf7, 0x23, 0xfa, 0x24, 0x8c,
	0x38, 0x4d, 0x2d, 0xbb, 0x2b, 0x4b, 0x76, 0xd7, 0x39, 0x99, 0x98, 0xcb, 0xeb, 0xde, 0x98, 0x4c,
	0xb0, 0x44, 0xdc, 0xdf, 0x55, 0xa0, 0xb9, 0xef, 0x1b, 0xb5, 0xe3, 0x45, 0x41, 0x95, 0x6b, 0x81,
	0x05, 0x64, 0xae, 0x1e, 0xa2, 0x81, 0xe5, 0x5a, 0x3c, 0x52, 0x20, 0xeb, 0xf3, 0x88, 0xa4, 0x6f,
	0x68, 0xaa, 0xe3, 0x27, 0x87, 0x89, 0x73, 0x3c, 0xa4, 0xa9, 0x0c, 0x9a, 0x06, 0x96, 0x6b, 0xe1,
	0xfc, 0x33, 0xe2, 0xbf, 0xa1, 0x71, 0xa0, 0x83, 0xc4, 0x90, 0xee, 0x1f, 0x2a, 0xb0, 0x9e, 0x99,
	0x22, 0x92, 0xa3, 0xec, 0x41, 0x99, 0xea, 0x1f, 0xfa, 0x41, 0x15, 0x85, 0x76, 0xa1, 0x79, 0x2e,
	0x4d, 0xd7, 0x59, 0xbb, 0xe5, 0x2d, 0xb9, 0x04, 0xeb, 0x7d, 0xf4, 0x31, 0xac, 0x11, 0x69, 0xa7,
	0xc9, 0xcd, 0x35, 0x4f, 0xd9, 0x8d, 0x0d, 0xee, 0x4e, 0x72, 0x81, 0x75, 0x14, 0x9f, 0x27, 0xd6,
	0xbd, 0x95, 0xdc, 0xbd, 0x96, 0x2d, 0xd5, 0x9c, 0x2d, 0x85, 0x10, 0xae, 0x95, 0x84, 0xf0, 0x5f,
	0x1b, 0xd0, 0x7c, 0xac, 0x22, 0xbe, 0xcc, 0xe9, 0x3d, 0x68, 0x24, 0xef, 0x62, 0x9a, 0x6a, 0xd1,
	0x8a, 0x10, 0xad, 0x41, 0x2e, 0x0e, 0x42, 0x36, 0x8d, 0xc8, 0x5c, 0xb6, 0x26, 0x25, 0xbc, 0x80,
	0xa3, 0x6d, 0xa8, 0x11, 0x3f, 0xd2, 0x51, 0x5c, 0xf7, 0xf6, 0x07, 0x43, 0x2c, 0x00, 0xa1, 0x9c,
	0x9f, 0x52, 0x69, 0xde, 0x01, 0xe1, 0xaa, 0xb5, 0xd4, 0x70, 0x0e, 0x13, 0x2d, 0x99, 0xa7, 0x24,
	0x66, 0xa1, 0xa8, 0x9c, 0x4d, 0x99, 0x25, 0x0b, 0x40, 0x18, 0xae, 0x1e, 0x3a, 0x70, 0xd6, 0x54,
	0x06, 0x69, 0x12, 0x1d, 0x41, 0x8f, 0x95, 0xcc, 0x24, 0x4e, 0x4b, 0x2a, 0x71, 0xd3, 0x2b, 0x1b,
	0x58, 0x70, 0xe9, 0x11, 0x84, 0xe1, 0xd6, 0xdb, 0xf2, 0x41, 0xc2, 0x69, 0x4b, 0x69, 0x8e, 0xb7,
	0x62, 0xd0, 0xc0, 0xab, 0x0e, 0xda, 0x2f, 0x06, 0xf9, 0x17, 0x3b, 0x82, 0xde, 0xbb, 0x92, 0x66,
	0xe3, 0x74, 0xb4, 0xe2, 0x65, 0x9d, 0x08, 0x97, 0x1e, 0x41, 0xf7, 0xa1, 0xee, 0x27, 0x29, 0x73,
	0xba, 0xf2, 0x28, 0xf2, 0x0a, 0xe5, 0x1d, 0xcb, 0x7d, 0xf4, 0x02, 0x9c, 0x74, 0x45, 0xf5, 0x70,
	0xd6, 0xe5, 0xd9, 0xdb, 0xde, 0xaa, 0xf2, 0x82, 0x57, 0x1e, 0x45, 0x4f, 0x60, 0x3b, 0x32, 0xe1,
	0x9f, 0x17, 0xba, 0x21, 0x43, 0x7e, 0xc3, 0xcb, 0x65, 0x19, 0x5e, 0xc1, 0xed, 0xfe, 0xb1, 0x02,
	0x6b, 0x27, 0x24, 0x95, 0x32, 0x8b, 0x95, 0xe8, 0xe7, 0x00, 0x53, 0x92, 0xf2, 0xe7, 0xb3, 0xcb,
	0xb3, 0x2c, 0x46, 0x2d, 0x44, 0x84, 0x34, 0x0b, 0x7f, 0xab, 0x82, 0xb3, 0x86, 0xe5, 0x5a, 0x60,
	0x94, 0x93, 0x89, 0xae, 0x15, 0x72, 0x2d, 0x82, 0x31, 0x22, 0x8c, 0x8f, 0x92, 0x20, 0x3c, 0x0f,
	0x69, 0x60, 0x82, 0xd1, 0xc6, 0xdc, 0x3f, 0x55, 0x60, 0x4d, 0x3f, 0xb5, 0x08, 0x4c, 0xf3, 0xb8,
	0xa6, 0x34, 0x2c, 0x80, 0xec, 0x86, 0xaa, 0x75, 0x43, 0x1f, 0x5a, 0x21, 0x1b, 0x12, 0x4e, 0x19,
	0xd7, 0xa9, 0x92, 0xd1, 0x85, 0xdb, 0xeb, 0xc5, 0xdb, 0x33, 0x4b, 0x1a, 0x0b, 0x4b, 0xdc, 0x7f,
	0xac, 0x41, 0xf3, 0xf8, 0xec, 0x7b, 0x31, 0xd0, 0xec, 0x40, 0x3b, 0x91, 0xab, 0x67, 0x99, 0x83,
	0x16, 0x80, 0x70, 0x93, 0xea, 0x6a, 0xd6, 0x10, 0x69, 0x21, 0x8b, 0x2c, 0xaf, 0xbd, 0x2f, 0xcb,
	0xeb, 0x2b, 0xb2, 0x5c, 0x64, 0x33, 0xf1, 0x2f, 0xc4, 0xe3, 0xf1, 0x34, 0x89, 0x74, 0x87, 0xce,
	0x61, 0xc8, 0x03, 0xe4, 0x27, 0x31, 0xa7, 0x31, 0x17, 0x27, 0x13, 0xa6, 0xa6, 0x2f, 0x55, 0x7f,
	0x4b, 0x76, 0xc4, 0x1c, 0xa9, 0xd1, 0xc3, 0xd8, 0x4f, 0x82, 0x30, 0x9e, 0xc8, 0x3c, 0x6f, 0xe3,
	0x65, 0x58, 0xf6, 0xd2, 0xab, 0x69, 0x98, 0x52, 0x26, 0x53, 0xbc, 0x8d, 0x0d, 0x29, 0x46, 0x07,
	0xcd, 0x3c, 0xa4, 0xf1, 0x84, 0x5f, 0xc8, 0xa4, 0x6d, 0xe3, 0x3c, 0x28, 0xbf, 0x55, 0x14, 0x30,
	0x9e, 0x4f, 0xa9, 0x4e, 0x4a, 0x1b, 0x12, 0x1e, 0xd4, 0xe4, 0x28, 0xf8, 0x85, 0x4c, 0xc7, 0x36,
	0xb6, 0x10, 0x74, 0x0f, 0x5a, 0xfa, 0xfd, 0x45, 0xc6, 0x89, 0x00, 0x6f, 0x99, 0xba, 0x80, 0xb3,
	0x9d, 0x42, 0x41, 0x5e, 0x2f, 0x16, 0xe4, 0x95, 0xb5, 0x6b, 0xe3, 0xc3, 0x6b, 0xd7, 0x43, 0xb8,
	0xa5, 0x4b, 0x83, 0x99, 0x1f, 0x87, 0x89, 0xca, 0x55, 0x67, 0x53, 0xde, 0xbc, 0x6a, 0xdb, 0x14,
	0xed, 0xad, 0xe5, 0xa2, 0x6d, 0x55, 0xae, 0xeb, 0xf9, 0xca, 0xb5, 0x0d, 0xcd, 0x90, 0x3d, 0x9f,
	0x45, 0x91, 0x83, 0x54, 0x77, 0x52, 0x94, 0x98, 0xca, 0x42, 0x76, 0x60, 0xf7, 0xe8, 0x1b, 0x6a,
	0x2a, 0xcb, 0xa3, 0xe8, 0x11, 0x6c, 0xa6, 0xf9, 0x86, 0xe7, 0xf4, 0x8a, 0xe3, 0x89, 0xc0, 0xf1,
	0x32, 0x63, 0x96, 0x1b, 0x37, 0xad, 0x2c, 0xbf, 0x07, 0xad, 0xa9, 0x2a, 0x1b, 0xcc, 0xd9, 0xd6,
	0x0f, 0xa2, 0xeb, 0x08, 0xce, 0x76, 0xb2, 0x61, 0xe4, 0xd6, 0xf2, 0x30, 0x52, 0xc8, 0x49, 0xa7,
	0x24, 0x27, 0x45, 0x4e, 0xc7, 0x21, 0x7f, 0x12, 0x91, 0x89, 0x73, 0x5b, 0xe7, 0xb4, 0xa6, 0x85,
	0x4e, 0x87, 0x63, 0x32, 0x71, 0xfa, 0xaa, 0x06, 0x88, 0x75, 0x36, 0x89, 0xdc, 0x59, 0x4c, 0x22,
	0xee, 0x43, 0xb8, 0x31, 0x0c, 0x19, 0x57, 0x2d, 0x98, 0x61, 0xca, 0xa6, 0x49, 0xcc, 0xa8, 0x18,
	0x11, 0x54, 0x7e, 0x8a, 0x6e, 0xaf, 0x46, 0x04, 0xc5, 0x82, 0x0d, 0xee, 0xfe, 0x0a, 0xba, 0x8f,
	0x09, 0xa3, 0xd9, 0x91, 0x1d, 0x68, 0x53, 0xf3, 0x95, 0x64, 0x4a, 0x40, 0x06, 0x88, 0xda, 0x79,
	0xc9, 0x4c, 0x49, 0x12, 0x4b, 0xf7, 0x67, 0xd0, 0x51, 0xe7, 0xe5, 0x87, 0xc3, 0xf2, 0x98, 0xe3,
	0xfe, 0xab, 0x02, 0x48, 0x68, 0xa6, 0x0a, 0x0c, 0x33, 0x6c, 0xdb, 0x66, 0x5c, 0x30, 0x53, 0x88,
	0x1e, 0x1e, 0x76, 0xa0, 0x7d, 0x40, 0xa3, 0xf0, 0x32, 0xe4, 0x59, 0x21, 0x5e, 0x00, 0xa2, 0xc0,
	0x1c, 0xdb, 0x05, 0x46, 0x12, 0xe8, 0x2b, 0x68, 0xaa, 0xc9, 0x48, 0x8f, 0x41, 0x1f, 0x79, 0xc5,
	0x0b, 0x3d, 0xc5, 0x71, 0x18, 0xf3, 0x74, 0x8e, 0x35, 0x7b, 0xff, 0x6b, 0xe8, 0x58, 0x70, 0x49,
	0x5f, 0xe8, 0x41, 0xe3, 0x2d, 0x89, 0x66, 0xa6, 0xd6, 0x29, 0xe2, 0x51, 0xf5, 0x61, 0xc5, 0xfd,
	0xc6, 0xb6, 0x2a, 0xf3, 0xdd, 0x67, 0xd0, 0xb1, 0xae, 0xce, 0x5c, 0xae, 0xb9, 0xec, 0x3d, 0xf7,
	0x37, 0x70, 0x5d, 0x05, 0xae, 0x02, 0x8e, 0xe2, 0xe9, 0x6c, 0xb5, 0x57, 0xb6, 0xa0, 0x26, 0x0a,
	0xb2, 0xf6, 0xba, 0x28, 0xc5, 0x3b, 0xd0, 0x7e, 0x99, 0x75, 0x0e, 0xe5, 0x8d, 0x05, 0xe0, 0xfe,
	0x1a, 0x36, 0x9e, 0x52, 0xfe, 0xff, 0x90, 0xfc, 0x0a, 0x36, 0x47, 0xb3, 0x88, 0x87, 0x22, 0xf4,
	0x5f, 0x4c, 0xa3, 0x84, 0x04, 0x1f, 0x20, 0xba, 0x0f, 0xad, 0x99, 0x3c, 0x93, 0xfd, 0x11, 0x93,
	0xd1, 0xee, 0x5f, 0x2a, 0xd0, 0x16, 0xfe, 0x11, 0xc9, 0xc5, 0xfe, 0x37, 0x32, 0xc5, 0xde, 0x88,
	0x5c, 0x49, 0x89, 0xba, 0x19, 0x66, 0xb4, 0xe8, 0x4a, 0x27, 0x59, 0x83, 0xd7, 0x25, 0x45, 0x35,
	0xc5, 0x02, 0xee, 0xde, 0x81, 0xc6, 0x58, 0xe8, 0x26, 0x32, 0x6f, 0x2c, 0x32, 0x4f, 0x3c, 0x6c,
	0x03, 0xcb, 0xb5, 0xcb, 0x61, 0x43, 0xfc, 0xee, 0xc9, 0xb2, 0x2b, 0x9b, 0xd8, 0xe7, 0x50, 0x8b,
	0x18, 0xd7, 0xaf, 0xef, 0x78, 0xf9, 0x5d, 0x6f, 0xc8, 0xb8, 0x8a, 0x42, 0xc1, 0xd4, 0xff, 0x12,
	0x5a, 0x06, 0xb0, 0xe3, 0xaf, 0xf1, 0xbe, 0xf8, 0xfb, 0x7b, 0x15, 0xd0, 0x53, 0xca, 0x85, 0xec,
	0x11, 0x99, 0x66, 0x01, 0x38, 0x84, 0xf5, 0xb1, 0x1c, 0x6c, 0x45, 0x5d, 0x1a, 0x91, 0xa9, 0x56,
	0xe2, 0xbe, 0x57, 0xe4, 0xf5, 0x72, 0x8c, 0x4a, 0xa5, 0xfc, 0x61, 0xf4, 0x2d, 0xb4, 0xa5, 0xf2,
	0xba, 0xdd, 0x0b, 0x49, 0x6e, 0xa9, 0x24, 0xc3, 0xa4, 0xa4, 0x2c, 0x0e, 0xf5, 0xbf, 0x03, 0x54,
	0xbc, 0xa6, 0xc4, 0xd0, 0x1d, 0xdb, 0xd0, 0xce, 0x5e, 0xd3, 0x93, 0xfe, 0xb6, 0x0c, 0xee, 0x8f,
	0xb4, 0x9b, 0xb3, 0x6b, 0x4a, 0xd2, 0xf5, 0x93, 0xbc, 0x94, 0xcd, 0x25, 0xd7, 0xdb, 0xfe, 0xfb,
	0xb1, 0x02, 0xbd, 0x17, 0xd3, 0x80, 0xc8, 0xfc, 0x1b, 0x51, 0x4e, 0xac, 0xc2, 0x74, 0x7c, 0xf6,
	0xfd, 0x62, 0xfc, 0xd1, 0x94, 0xe8, 0xdc, 0x8f, 0x0b, 0xb3, 0xcf, 0x02, 0x41, 0xbf, 0x84, 0xb5,
	0x53, 0xca, 0xb9, 0x98, 0x2e, 0x6a, 0xda, 0x53, 0x65, 0xf2, 0x3d, 0xcd, 0xa4, 0x3c, 0x65, 0x8e,
	0xf4, 0x1f, 0x41, 0xd7, 0xde, 0xf8, 0xa0, 0x52, 0xf4, 0x25, 0x74, 0x4f, 0xed, 0xce, 0x8f, 0xa0,
	0x6e, 0xfd, 0x8b, 0x28, 0xd7, 0x59, 0xe0, 0xea, 0x8f, 0x5e, 0x19, 0xb8, 0x07, 0x70, 0xfb, 0x29,
	0xe5, 0xf6, 0x51, 0xba, 0x68, 0x1c, 0x9f, 0xc2, 0x9a, 0xaf, 0x20, 0x1d, 0x42, 0xeb, 0x9e, 0xcd,
	0x89, 0xcd, 0xee, 0xde, 0x8f, 0x75, 0xa8, 0x9e, 0x3e, 0x40, 0x0f, 0x54, 0xe5, 0xd3, 0xfd, 0x07,
	0x75, 0x3d, 0xab, 0x27, 0xf4, 0x7b, 0x5e, 0x49, 0x6f, 0x72, 0xaf, 0xa1, 0x5d, 0xe8, 0x0e, 0xc4,
	0x77, 0x1a, 0xd5, 0xd9, 0x6d, 0x9a, 0x53, 0x7f, 0xdd, 0xb3, 0x5b, 0x92, 0xe2, 0x54, 0xd5, 0xf2,
	0xbd, 0x9c, 0x1f, 0x41, 0xfb, 0x29, 0xe5, 0xcb, 0x6c, 0x66, 0xe1, 0x5e, 0x43, 0x5f, 0xe7, 0x6a,
	0x34, 0xba, 0x51, 0xd2, 0x2c, 0xfa, 0x36, 0x58, 0xa6, 0xaf, 0x9e, 0x96, 0x4d, 0x65, 0x2f, 0xd5,
	0x37, 0x7b, 0xfd, 0x9f, 0xe6, 0xfc, 0x54, 0xea, 0xab, 0xd9, 0x36, 0xbd, 0x7c, 0xd9, 0xee, 0x9b,
	0x73, 0xee, 0x35, 0xf4, 0xc0, 0xb8, 0x40, 0xf3, 0x22, 0xaf, 0xd0, 0x3f, 0x8a, 0xd2, 0xbf, 0x00,
	0x58, 0xe4, 0xeb, 0xd2, 0xab, 0xdc, 0x28, 0x49, 0x65, 0xf7, 0x1a, 0xfa, 0x0a, 0xd6, 0x73, 0x81,
	0x8b, 0x6e, 0x96, 0x06, 0x72, 0xf1, 0xae, 0x6f, 0xe0, 0x7a, 0x21, 0x9e, 0x96, 0xae, 0xec, 0x7b,
	0x2b, 0x23, 0xce, 0xbd, 0x76, 0xd6, 0x94, 0xff, 0x55, 0x3f, 0xf8, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x90, 0x2a, 0x2c, 0x5d, 0xbb, 0x18, 0x00, 0x00,
}
